### PR TITLE
configure libvirt to use ssh

### PR DESCRIPTION
**Pull request by justinjpacheco**
- configure nova-compute to use the qemu+ssh schema when executing
    live migrations
  - configure libvirt to no longer listen for incoming tcp connections

### CODE REVIEW

**Comment by furlongm** [comment]
Does this affect the time to live migrate an instance?

**Comment by justinjpacheco** [comment]
i'll test with the largest flavor available, but it seems to be as fast as the default method

**Comment by justinjpacheco** [comment]
@comay yah, im not sure

**Comment by justinjpacheco** [comment]
@furlongm migration time seems to be unaffected. i tested with the largest flavor between two hypervisors, they appear to be the same

**Comment by furlongm** [comment]
Line 18 seems to have an extra space at the start of the line, perhaps that's throwing things off? Although, it should just be showing an extra space there in the diff?

**Comment by justinjpacheco** [comment]
@furlongm doesn't look like it made a difference :(

**Comment by furlongm** [comment]
Actually it seems like a bunch of whitespace has been added at the end of those lines too.

**Comment by furlongm** [comment]
Looks like a tab at the end of each line.

**Comment by justinjpacheco** [comment]
@furlongm fixed

**Pull request merged**
