### PR TITLE
Update Cinder default volumes quota from 10 to -1

### PR DESCRIPTION
**Pull request by dkaplan34**
Update Cinder default volumes quota from 10 to -1

### CODE REVIEW

**Comment by kamidzi** [comment]
@dkaplan34, could you add some context around this change?

**Comment by dkaplan34** [comment]
This will enable users to create unlimited volumes since they are restricted gigabytes quota

**Comment by kamidzi** [comment]
I don't think it's sufficient to just update the configuration file. See: https://bugs.launchpad.net/cinder/+bug/1461563

The following demonstrates:
```
# read user pw host db < <(sed -n 's%^connection.*://\(.*\):\(.*\)@\(.*\)\/\(.*\)$%\1 \2 \3 \4%p' /etc/cinder/cinder.conf) ; mysql -u $user -D $db -h $host -p$pw -e 'select * from quota_classes ; ' ; cinder absolute-limits ; cinder quota-class-update --volumes -1 default ; cinder absolute-limits
Warning: Using a password on the command line interface can be insecure.
+---------------------+------------+------------+---------+----+------------+-------------------+------------+
| created_at          | updated_at | deleted_at | deleted | id | class_name | resource          | hard_limit |
+---------------------+------------+------------+---------+----+------------+-------------------+------------+
| 2015-09-01 18:45:31 | NULL       | NULL       |       0 |  1 | default    | volumes           |         10 |
| 2015-09-01 18:45:31 | NULL       | NULL       |       0 |  2 | default    | snapshots         |         10 |
| 2015-09-01 18:45:31 | NULL       | NULL       |       0 |  3 | default    | gigabytes         |       1000 |
| 2015-09-01 18:45:31 | NULL       | NULL       |       0 |  4 | default    | consistencygroups |         10 |
+---------------------+------------+------------+---------+----+------------+-------------------+------------+
+--------------------------+-------+
|           Name           | Value |
+--------------------------+-------+
| maxTotalBackupGigabytes  |  1000 |
|     maxTotalBackups      |   10  |
|    maxTotalSnapshots     |   10  |
| maxTotalVolumeGigabytes  |  1000 |
|     maxTotalVolumes      |   10  |
| totalBackupGigabytesUsed |   0   |
|     totalBackupsUsed     |   0   |
|    totalGigabytesUsed    |   0   |
|    totalSnapshotsUsed    |   0   |
|     totalVolumesUsed     |   0   |
+--------------------------+-------+
ERROR: 'NoneType' object has no attribute '_info'
+--------------------------+-------+
|           Name           | Value |
+--------------------------+-------+
| maxTotalBackupGigabytes  |  1000 |
|     maxTotalBackups      |   10  |
|    maxTotalSnapshots     |   10  |
| maxTotalVolumeGigabytes  |  1000 |
|     maxTotalVolumes      |   -1  |
| totalBackupGigabytesUsed |   0   |
|     totalBackupsUsed     |   0   |
|    totalGigabytesUsed    |   0   |
|    totalSnapshotsUsed    |   0   |
|     totalVolumesUsed     |   0   |
+--------------------------+-------+
```

**Comment by erhudy** [comment]
It won't change the quota for existing clusters (we'll need to reset that by hand), but I think this is okay to merge as a change for the future. Since it costs nothing to create a volume, whether a user wants to divide their chunk of space up 5 ways or 500 ways should be up to them.

**Pull request merged**
