### PR TITLE
Limit loading of CloudCollector to head nodes

### LINKED ISSUE #896: Diamond CloudCollector should be disabled on monitoring cluster
On a monitoring cluster:

`[2015-11-05T16:46:03+00:00] ERROR: template[/etc/diamond/collectors/CloudCollector.conf] (bcpc::diamond line 133) had an error: RuntimeError: No config found for get_config(mysql-root-user)!!!`

### PR DESCRIPTION
**Pull request by kelvk**
Fixes #896

### CODE REVIEW

**Comment by kamidzi** [comment]
What about just testing for the role, like:
```
chef > puts 'do diamond' if node.roles.include?('BCPC-Headnode')
 => nil
chef > node.fqdn
 => "bcpc-vm4.hypervisor-bcpc.example.com"
```

**Comment by kelvk** [comment]
I am trying to avoid making trips to the Chef server (I think that `node.roles` does) hence a local file test. I can apply your suggestion if this is the desired pattern.

**Comment by kamidzi** [comment]
I believe L145 will still ensure that diamond starts up?

```
root@bcpc-vm4:~# sed -n 145p /var/chef/cache/cookbooks/bcpc/recipes/diamond.rb
        only_if "test -d /var/lib/mysql/nova"
root@bcpc-vm4:~# status diamond && service diamond stop && chef-client -obcpc::diamond &>/dev/null && status diamond
diamond start/running, process 26214
diamond stop/waiting
diamond start/running, process 29349
```

**Comment by kelvk** [comment]
Yes, so does L148.

**Comment by kamidzi** [comment]
Right, correction: I meant the block beginning on L148. I believe that would also need to be wrapped with a guard.

**Comment by kelvk** [comment]
Do you mean Diamond should be disabled and stopped if `node['bcpc']['enabled']['metrics']` is false? If sio, I can see the usefulness of that during decommissioning, though it's probably better fit for separate issue.

**Comment by kamidzi** [comment]
Well--I didn't even think of that--it would be a nice feature. I just mean in my testing, diamond still attempts to start on nodes that are `BCPC-Monitoring` and node `BCPC-Headnode` because of the service definition `start` action

**Comment by kamidzi** [comment]
So, I misunderstood the purpose of this and conflated the service with the config. Looks good.

**Pull request merged**
