### PR TITLE
Don't hardcode the PNL mirror in the bootstrap sources.list template

### PR DESCRIPTION
**Pull request by erhudy**
derp

### CODE REVIEW

**Comment by kamidzi** [comment]
What about using the indirect paths prefixed by `/bcpc/mirror-root`.  Just in case one is forced to migrate mirrors?

**Comment by erhudy** [comment]
I'm okay with that, but it would require re-ordering some other tasks so that the symlinks are set up before the first `apt-get update`. This was the minimal-effort fix.

**Comment by erhudy** [comment]
Force pushed over the old changeset with a new one that moves the symlink mapping up above the template creation, and replaces the paths in the template with ones derived from `{{ bootstrap_mirror_root_dir }}`.

**Comment by kamidzi** [comment]
Tested local apt sources change with `ansible-playbook --tags configure_apt -v -i  <inventory-file> bootstrap_deployment/converge-bootstrap.yml`

**Pull request merged**
