### PR TITLE
Deploy ProxySQL

### PR DESCRIPTION
**Pull request by kelvk**
As a way to scale MySQL, I propose to introduce [ProxySQL](http://www.proxysql.com/) to load-balance and proxy MySQL traffic instead of using HAProxy. Benefits of using ProxySQL:
- Ability to split read/write requests, so the currently idle MySQL instances can handle some `SELECT` workload.
- Able to detect the state of MySQL backends (i.e. is it being synced), so MySQL instances that have not fully joined the cluster do not serve traffic.
- When a higher-priority instance rejoins current HAProxy rotation, MySQL requests (including writes) are split between two instances. This is undesirable due to potential locks. ProxySQL attempts to limit writes to only one instance.

This is enabled by default on a local build cluster (via environment files), so physical cluster builds will need to be explicitly configured to enable ProxySQL usage. On a relatively small, under-utilized cluster that I run, the observable performance difference between proxied and non-proxied requests for PowerDNS, `dns_fill.py`, backups and nova queries appear negligible.

Things that you may want to test/verify (on multi-head cluster):
1. Read/write traffic split
2. Recovery on VIP migration
3. Detection of backend MySQL instance states by ProxySQL
4. Functionality of Openstack in general and `dns_fill.py`, cluster backups, PowerDNS

Whilst the high-level state of ProxySQL is monitored by Keepalived, I intend to add another PR for monitoring by Zabbix after this is merged.

### CODE REVIEW

**Comment by erhudy** [comment]
Build failed as soon as it tried to converge the bootstrap node (I merged this branch onto current master before starting the build).
```
================================================================================
Recipe Compile Error in /var/chef/cache/cookbooks/bcpc-proxysql/attributes/default.rb
================================================================================

NoMethodError
-------------
undefined method `[]' for nil:NilClass

Cookbook Trace:
---------------
  /var/chef/cache/cookbooks/bcpc/libraries/utils.rb:81:in `rescue in init_config'
  /var/chef/cache/cookbooks/bcpc/libraries/utils.rb:72:in `init_config'
  /var/chef/cache/cookbooks/bcpc/libraries/utils.rb:87:in `make_config'
  /var/chef/cache/cookbooks/bcpc-proxysql/attributes/default.rb:7:in `from_file'

Relevant File Content:
----------------------
/var/chef/cache/cookbooks/bcpc/libraries/utils.rb:

 74:          $edbi = Chef::EncryptedDataBagItem.load('configs', node.chef_environment) if node['bcpc']['enabled']['encrypt_data_bag']
 75:          Chef::Log.info("============ Loaded existing data_bag_item \"configs/#{node.chef_environment}\"")
 76:      rescue
 77:          $dbi = Chef::DataBagItem.new
 78:          $dbi.data_bag('configs')
 79:          $dbi.raw_data = { 'id' => node.chef_environment }
 80:          $dbi.save
 81>>         $edbi = Chef::EncryptedDataBagItem.load('configs', node.chef_environment) if node['bcpc']['enabled']['encrypt_data_bag']
 82:          Chef::Log.info("++++++++++++ Created new data_bag_item \"configs/#{node.chef_environment}\"")
 83:      end
 84:  end
 85:  
 86:  def make_config(key, value, force=false)
 87:      init_config if $dbi.nil?
 88:      if $dbi[key].nil? or force
 89:          $dbi[key] = (node['bcpc']['enabled']['encrypt_data_bag']) ? Chef::EncryptedDataBagItem.encrypt_value(value, Chef::EncryptedDataBagItem.load_secret) : value
 90:          $dbi.save
```

**Comment by kelvk** [comment]
Discussed with @erhudy earlier offline that the error seem to be caused by a non-standard Chef environment, as it was not reproducible with the provided `Test-Laptop-Vagrant` environment. I have also just pushed a commit to parameterize more ProxySQL options.

**Comment by erhudy** [comment]
This is getting repeatedly output into `/var/lib/proxysql/proxysql.log`:
```
2016-11-11 21:39:50 [INFO] New mysql_replication_hostgroups table
writer_hostgroup: 0 , reader_hostgroup: 1, bcpc
Warning: Using a password on the command line interface can be insecure.
Warning: Using a password on the command line interface can be insecure.
Warning: Using a password on the command line interface can be insecure.
Warning: Using a password on the command line interface can be insecure.
2016-11-11 21:39:51 [INFO] Received LOAD MYSQL SERVERS TO RUNTIME command
HID: 1 , address: 10.0.100.11 , port: 3306 , weight: 1 , status: ONLINE , max_connections: 3000 , max_replication_lag: 0 , use_ssl: 0 , max_latency_ms: 0 , comment: 
HID: 0 , address: 10.0.100.11 , port: 3306 , weight: 1 , status: ONLINE , max_connections: 3000 , max_replication_lag: 0 , use_ssl: 0 , max_latency_ms: 0 , comment: 
HID: 1 , address: 10.0.100.11 , port: 3306 , weight: 1 , status: ONLINE , max_connections: 3000 , max_replication_lag: 0 , use_ssl: 0 , max_latency_ms: 0 , comment: 
HID: 0 , address: 10.0.100.11 , port: 3306 , weight: 1 , status: ONLINE , max_connections: 3000 , max_replication_lag: 0 , use_ssl: 0 , max_latency_ms: 0 , comment: 
HID: 1 , address: 10.0.100.11 , port: 3306 , weight: 1 , status: ONLINE , max_connections: 3000 , max_replication_lag: 0 , use_ssl: 0 , max_latency_ms: 0 , comment: 
HID: 0 , address: 10.0.100.11 , port: 3306 , weight: 1 , status: ONLINE , max_connections: 3000 , max_replication_lag: 0 , use_ssl: 0 , max_latency_ms: 0 , comment: 
```

**Comment by erhudy** [comment]
Backup script on bootstrap node fails because `/root/.my.monitoring.cnf` gets the port number from **bcpc.ports.mysql**, but ProxySQL is only running on the compute side, not on the monitoring side, so nothing is listening on 6033:
```
root@bcpc-vm-bootstrap:/home/vagrant# /usr/local/bin/bcpc_backup.sh /var/backups/bcpc daily
ERROR 2003 (HY000): Can't connect to MySQL server on '10.0.100.6' (111)
ERROR 2003 (HY000): Can't connect to MySQL server on '10.0.100.6' (111)
ERROR 2003 (HY000): Can't connect to MySQL server on '10.0.100.6' (111)

root@bcpc-vm-bootstrap:/home/vagrant# cat /root/.my.main.cnf 
[client]
host=10.0.100.5
port=6033
user=mysql_backup
password=3NJ5jX2HVvUQLq_egYnW

root@bcpc-vm-bootstrap:/home/vagrant# cat /root/.my.monitoring.cnf 
[client]
host=10.0.100.6
port=6033
user=mysql_backup
password=3NJ5jX2HVvUQLq_egYnW
```

**Comment by erhudy** [comment]
`/var/lib/proxysql/check.log` is also spamming:
```
Fri Nov 11 21:53:30 UTC 2016 Enabling config
Warning: Using a password on the command line interface can be insecure.
Warning: Using a password on the command line interface can be insecure.
Fri Nov 11 21:53:31 UTC 2016 Check server 0:10.0.100.11:3306 , status ONLINE , wsrep_local_state 4
Warning: Using a password on the command line interface can be insecure.
Fri Nov 11 21:53:31 UTC 2016 Check server 1:10.0.100.11:3306 , status ONLINE , wsrep_local_state 4
Fri Nov 11 21:53:31 UTC 2016 Number of writers online: 1 : hostgroup: 0
```

**Comment by kelvk** [comment]
The repeated events in `/var/lib/proxysql/proxysql.log` are generated by the scheduled monitoring job in ProxySQL. It executes `LOAD MYSQL SERVERS TO RUNTIME` every time it runs.

```
mysql> select * from runtime_scheduler;
+----+--------+-------------+----------------------------------+------+------+------+------+-----------------------------+---------+
| id | active | interval_ms | filename                         | arg1 | arg2 | arg3 | arg4 | arg5                        | comment |
+----+--------+-------------+----------------------------------+------+------+------+------+-----------------------------+---------+
| 1  | 1      | 1000        | /usr/bin/proxysql_galera_checker | 0    | 1    | 1    | 1    | /var/lib/proxysql/check.log | bcpc    |
+----+--------+-------------+----------------------------------+------+------+------+------+-----------------------------+---------+
```

```
$ cat /usr/bin/proxysql_galera_checker
...
$PROXYSQL_CMDLINE "LOAD MYSQL SERVERS TO RUNTIME;" 2>> ${ERR_FILE}

exit 0
```

**Comment by erhudy** [comment]
I guess we can't squelch that without also squelching potentially useful logging information.

**Comment by kelvk** [comment]
To be exact, the execution of `LOAD MYSQL SERVERS TO RUNTIME` causes ProxySQL to log the event.

`/var/lib/proxysql/check.log` is the log file for the scheduled job.

We could run a customized checker script (which some people do for customized check algorithms) to address these concerns, though probably not as first pass for us until we get more comfortable with this tool.

**Comment by kelvk** [comment]
True on the backup complaint. We typically run Openstack and monitoring services on separate clusters, so while not negatively impacting, it would be nice to squash the complaint.

**Comment by kelvk** [comment]
Rebased and modify backup recipe to always use port 3306 for monitoring database.

**Comment by kelvk** [comment]
Out of date, and will likely require even more changes when we move beyond Mitaka. Closing for now.

**Pull request closed without merging**
