### PR TITLE
Manage RGW user quotas

### PR DESCRIPTION
**Pull request by kelvk**
Per #806, quota limits are not enforced by default for users created in RadosGW via Keystone integration. This PR enables and sets either a default or predefined `max_size` [quota](http://ceph.com/docs/master/radosgw/admin/#set-user-quota) for each RGW user. 

Quota enforcement can be tested by adding `tester` to `default['bcpc']['rgw_quota']['user']` with `max_size` of `1`. When applied, `check rgw` will fail on `QuotaExceeded`.

### CODE REVIEW

**Comment by erhudy** [comment]
Testing.

**Comment by erhudy** [comment]
It wasn't working at first until I realized the recipe wasn't being included anywhere. Can you update the appropriate role to add **bcpc::rgw-quota**?

**Comment by erhudy** [comment]
After adding the recipe and re-running, got the expected results with tester before changing the quota (check worked) and after dropping the quota to 1:
```
+------+-------+-------+---------------------------------------------------------------------------------+
| name | state |  time |                                       msg                                       |
+------+-------+-------+---------------------------------------------------------------------------------+
| rgw  | ERROR | 0.302 |                          S3ResponseError: 403 Forbidden                         |
|      |       |       | <?xml version="1.0" encoding="UTF-8"?><Error><Code>QuotaExceeded</Code></Error> |
+------+-------+-------+---------------------------------------------------------------------------------+
```

**Comment by kelvk** [comment]
My bad. `BCPC-Headnode` role updated.

**Pull request merged**
