### PR TITLE
UCA baseline move: Ceph 15.2.16 and new Ussuri patches

### PR DESCRIPTION
**Pull request by tj90241**
These changes allow `chef-bcpc` to be built against the
Ussuri UCA as it appears upstream today.

This includes removing some in-tree patches that we had
which are now available upstream, leveraging the
recently added `python3-osc-placement` packaging, and
rebasing remaining changes we have to OpenStack against
upstream changes.

### CODE REVIEW

**Comment by tj90241** [comment]
1h1w and 3h3w builds passed.

**Comment by tj90241** [comment]
The `api-paste.ini` file for Nova now only contains our additions for the `/healthcheck` path:
```
--- nova-common/etc/nova/api-paste.ini	2021-11-12 16:58:39.000000000 +0000
+++ /etc/nova/api-paste.ini	2022-05-04 15:50:40.314014231 +0000
@@ -18,6 +18,7 @@
 [composite:osapi_compute]
 use = call:nova.api.openstack.urlmap:urlmap_factory
 /: oscomputeversions
+/healthcheck: healthcheck
 /v2: oscomputeversion_legacy_v2
 /v2.1: oscomputeversion_v2
 # v21 is an exactly feature match for v2, except it has more stringent
@@ -28,6 +29,10 @@
 /v2/+: openstack_compute_api_v21_legacy_v2_compatible
 /v2.1/+: openstack_compute_api_v21
 
+[app:healthcheck]
+use = egg:oslo.middleware#healthcheck
+detailed = False
+
 [composite:openstack_compute_api_v21]
 use = call:nova.api.auth:pipeline_factory_v21
 keystone = cors http_proxy_to_wsgi compute_req_id faultwrap request_log sizelimit osprofiler authtoken keystonecontext osapi_compute_app_v21
 ```

**Comment by tj90241** [comment]
And, finally, `heat-common`:
```
--- heat-common/etc/heat/api-paste.ini	2021-08-30 13:01:25.000000000 +0000
+++ /etc/heat/api-paste.ini	2022-05-04 15:54:37.960746341 +0000
@@ -1,7 +1,7 @@
 
 # heat-api pipeline
 [pipeline:heat-api]
-pipeline = cors request_id faultwrap http_proxy_to_wsgi versionnegotiation authurl authtoken context osprofiler apiv1app
+pipeline = healthcheck cors request_id faultwrap http_proxy_to_wsgi versionnegotiation authurl authtoken context osprofiler apiv1app
 
 # heat-api pipeline for standalone heat
 # ie. uses alternative auth backend that authenticates users against keystone
@@ -31,13 +31,17 @@
 
 # heat-api-cfn pipeline
 [pipeline:heat-api-cfn]
-pipeline = cors request_id http_proxy_to_wsgi cfnversionnegotiation ec2authtoken authtoken context osprofiler apicfnv1app
+pipeline = healthcheck cors request_id http_proxy_to_wsgi cfnversionnegotiation ec2authtoken authtoken context osprofiler apicfnv1app
 
 # heat-api-cfn pipeline for standalone heat
 # relies exclusively on authenticating with ec2 signed requests
 [pipeline:heat-api-cfn-standalone]
 pipeline = cors request_id http_proxy_to_wsgi cfnversionnegotiation ec2authtoken context apicfnv1app
 
+[filter:healthcheck]
+use = egg:oslo.middleware#healthcheck
+detailed = False
+
 [app:apiv1app]
 paste.app_factory = heat.common.wsgi:app_factory
 heat.app_factory = heat.api.openstack.v1:API
 ```

**Review by comay — COMMENTED** [review]
Nice work, Tyler. So just to confirm:

1. All of the Paste files match the versioned delivered by the new baselined packages with the exception of the `healthcheck` stanzas?

2. Was `nova/api.py` the only patched file we have that needed to be repatched? The others haven't changed at all from the earlier baseline?

**Pull request merged**
