### PR TITLE
Rework Zabbix host discovery for auto host registration

### PR DESCRIPTION
**Pull request by kelvk**
This reworks Zabbix host registration that existed in RC2/3. 

Zabbix will discover hosts every 10 minutes in the management network by default, then associates them to appropriate template and hostgroup (BCPC-Headnode, BCPC-Worknode, BCPC-Monitoring). These templates will likely be evolving as there appears room for checks/triggers expansion. For reviewer(s), I'd say the committed xml files can be safely ignored.

### CODE REVIEW

**Comment by erhudy** [comment]
Is this PR independent of #629 or does it also have the content of #629?

**Comment by kelvk** [comment]
It does depend on #629 .

**Comment by erhudy** [comment]
I mean, this PR appears to have a lot of the same content as #629. Does this make #629 redundant?

**Comment by kelvk** [comment]
Closed #629.

**Comment by erhudy** [comment]
Took autodiscovery for a test drive and it worked as advertised. I will merge this by COB.

**Pull request merged**
