### PR TITLE
Upgrade Kibana to latest stable version

### PR DESCRIPTION
**Pull request by kkoh61**
https://www.elastic.co/downloads/kibana

### CODE REVIEW

**Comment by erhudy** [comment]
One minor issue: when accessing through HAProxy, the URL `/kibana` does not work, but `/kibana/` with the trailing slash does work.

**Comment by erhudy** [comment]
Other than that, everything seems fine on Trusty.

**Comment by kkoh61** [comment]
Updated to append slash if it's missing.

**Comment by erhudy** [comment]
Seems fine to me otherwise. If we're not using `/etc/apache2/sites-available/kibana-web` any more, maybe delete that as cleanup. Everything worked fine on Trusty, so I think it's good to merge if everything was happy on Precise.

**Comment by kkoh61** [comment]
Good reminder. Updated PR once more to remove old files in the code base. However, I am not explicitly removing the configuration on deployed systems as I don't believe Kibana is widely enabled.

**Pull request merged**
