### PR TITLE
- Remove packages installed only because of apt recommends by using

### PR DESCRIPTION
**Pull request by mihalis68**
--no-install-recommends everywhere
- explicitly install python-setuptools instead of getting via recommends
- remove kexec recipe from the core chef "node" role
- remove kexec.rb chef recipe

- move kexec configuration to ansible too

*Issue number of the reported bug or feature request: #<number>*

**Describe your changes**
A clear and concise description of the changes you have made.

**Testing performed**
Describe the testing you have performed to ensure that the bug has been addressed, or that the new feature works as planned.

**Additional context**
Add any other context about your contribution here.

### CODE REVIEW

**Review by comay — COMMENTED** [review]
Chris, is chef/cookbooks/bcpc/files/default/kexec/default being removed? I didn't see it marked explicitly removed or it seems "git mv"ed to ansible/playbooks/roles/common/templates/kexec/default.j2 but perhaps that's not properly recorded by GitHub.

**Comment by mihalis68** [comment]
> Chris, is chef/cookbooks/bcpc/files/default/kexec/default being removed? I didn't see it marked explicitly removed or it seems "git mv"ed to ansible/playbooks/roles/common/templates/kexec/default.j2 but perhaps that's not properly recorded by GitHub.

Good point. I've removed it!

**Comment by mihalis68** [comment]
The impact of removing the extra packages obtained from recommended is shown in this gist which has before, after and a diff https://gist.github.com/mihalis68/0cfaebef3633b383a584cbd46be1ef9c

**Review by comay — COMMENTED** [review]
There are a set of packages that aren't covered here - namely those installed via Ansible and ad-hoc `apt-get` installs in scripts.

ansible/playbooks/roles/chef-node/tasks/chef-node.yml                   chef
ansible/playbooks/roles/chef-server/tasks/chef-server.yml               chef-server-core
ansible/playbooks/roles/chef-workstation/tasks/chef-workstation.yml     chef
ansible/playbooks/roles/common/tasks/configure-bgp.yml                  bird2
ansible/playbooks/roles/common/tasks/configure-chrony.yml               chrony
ansible/playbooks/roles/common/tasks/configure-local-proxy.yml          tinyproxy
ansible/playbooks/roles/common/tasks/configure-resolver.yml             unbound
ansible/playbooks/roles/common/tasks/configure-system.yml               linux-*
ansible/playbooks/roles/common/tasks/configure-system.yml               kexec-tools
ansible/playbooks/roles/common/tasks/configure-system.yml               amd64-microcode
ansible/playbooks/roles/common/tasks/configure-system.yml               intel-microcode
virtual/network/provisioner.sh                                          lldpd
virtual/network/provisioner.sh                                          traceroute
virtual/network/provisioner.sh                                          bird2
virtual/network/provisioner.sh                                          iptables-persistent
virtual/provisioners/finish.sh                                          linux-*

Perhaps a more straightforward solution here would be to make this the default by setting

APT::Get::Install-Recommends "false";

in /etc/apt/apt.conf (thanks to @desrod for the line)?

**Comment by tj90241** [comment]
@comay 👏 that is a MUCH better solution!  Will give it a spin.

The `python-setuptools` addition is because we now are not getting it for free as a recommended-package, and it's needed to run `setup.py` for `etcd3gw`.  We can possibly install `setuptools` in the `venv` there (and elsewhere?) if that's desirable.  (this is unfortunately another problem that would be solved by consuming this package directly from Canonical).

**Comment by comay** [comment]
Looks like it's the latter name, at least according to

```
$ `apt-config dump APT::Install-Recommends`
APT::Install-Recommends "1";
```

so setting it to "0" should do the trick.

**Comment by comay** [comment]
> The `python-setuptools` addition is because we now are not getting it for free as a recommended-package, and it's needed to run `setup.py` for `etcd3gw`. We can possibly install `setuptools` in the `venv` there (and elsewhere?) if that's desirable. (this is unfortunately another problem that would be solved by consuming this package directly from Canonical).

👍🏻

**Comment by mihalis68** [comment]
I think futurist is something we need that we don't get without installing the recommended packages i.e. a hidden dependency. However I think th suggestion of setting apt:;install-recommends is much cleaner. Perhaps we should nuke this PR and start again clean? I have no problem with that. I can take it on again, but it seems @tj90241 may already be doing so.

**Comment by comay** [comment]
It's not `python-futurist` but rather the addition of `python-setuptools` but Tyler explained why that was necessary.

**Comment by tj90241** [comment]
I haven't started yet, @mihalis68 , if you are interested.

**Comment by mihalis68** [comment]
yep I'll take this one again. can you stop the race condition I showed you?

**Comment by tj90241** [comment]
yeah, I'll take a crack at that in a second.

**Comment by mihalis68** [comment]
Replaced by the superior (much smaller) https://github.com/bloomberg/chef-bcpc/pull/1841

**Pull request closed without merging**
