### PR TITLE
Toggle for enabling/disabling swap

### PR DESCRIPTION
**Pull request by kelvk**
Addresses #808.

### CODE REVIEW

**Comment by erhudy** [comment]
Testing.

**Comment by erhudy** [comment]
While this works on local builds, I do not think it will work on hardware installs. The swap lines in `/etc/fstab` take the following format there:
```
# swap was on /dev/sda2 during installation
UUID=8f9a1217-ffc9-4690-a291-207f96556faa none            swap    sw              0       0
```

**Comment by kelvk** [comment]
Pushed an updated commit.

**Comment by erhudy** [comment]
Retesting.

**Comment by erhudy** [comment]
Tested locally and on hardware by cheffing in, disabling swap via attribute and recheffing, then enabling swap via attribute and recheffing, in order to verify that it reactivates appropriately and comments/uncomments the correct line in `/etc/fstab`.

**Pull request merged**
