### PR TITLE
Add some checks for case of re-provision during swap creation

### LINKED ISSUE #847: Re-running vagrant shell provisioners can often fail
I've experienced the following:
```
==> vm6: Running provisioner: add-swap-space (shell)...
    vm6: Running: inline script
==> vm6: fallocate:
==> vm6: /swap: fallocate failed
==> vm6: :
==> vm6: Text file busy
==> vm6: Setting up swapspace version 1, size = 8388604 KiB
==> vm6: no label, UUID=97e4a657-b4a2-4a7c-a246-32851545c592
==> vm6: swapon:
==> vm6: /swap: swapon failed
==> vm6: :
==> vm6: Device or resource busy
==> vm6: /swap none swap defaults 0 0
```

The vm will still come up

### PR DESCRIPTION
**Pull request by kamidzi**
Fixes #847

### CODE REVIEW

**Comment by erhudy** [comment]
Without fix in place, `vagrant provision` on an existing instance results in the following:
```
==> bootstrap: Running provisioner: add-swap-space (shell)...
    bootstrap: Running: inline script
==> bootstrap: fallocate: /swap: fallocate failed: Text file busy
==> bootstrap: Setting up swapspace version 1, size = 8388604 KiB
==> bootstrap: no label, UUID=64cc1b9f-9f08-47e9-b04d-4549ab80949d
==> bootstrap: swapon: /swap: swapon failed: Device or resource busy
==> bootstrap: /swap none swap defaults 0 0
```

**Comment by erhudy** [comment]
With fix in place:
```
==> bootstrap: Running provisioner: add-swap-space (shell)...
    bootstrap: Running: inline script
==> bootstrap: /swap                                   file		8388604	0	-1
==> bootstrap: Setting up swapspace version 1, size = 8388604 KiB
==> bootstrap: no label, UUID=22991fcc-be6b-41e5-a950-7243c277b51f
==> bootstrap: /swap none swap defaults 0 0
```

**Comment by erhudy** [comment]
If re-provisioning the VM, should it deactivate and reactivate the swap, or just continue on as a no-op if the swap file is already there and active?

**Comment by kamidzi** [comment]
I wondered about that, and left it to do the latter in case one wants to change the swap size - a minor mod maybe required for that, but I left it to reprovision.

**Pull request merged**
