### PR TITLE
More minor cleanup, rewrites of binary and apt package version detection

### PR DESCRIPTION
**Pull request by desrod**
Small fixes to add some error checking, exit codes, rewrote the checks for required binaries, apt package version comparison, pulling things closer to the bash style guide with regard to variable naming conventions and syntax. Merges clean with bloomberg/master at the time of this PR.

### CODE REVIEW

**Comment by mihalis68** [comment]
I'm in favor of no tabs and/or using that tool. Letting Marcus and David finish that convo, but otherwise ok to merge.

**Comment by mihalis68** [comment]
@desrod @furlongm did you finish the debate about tabs/spaces?

**Comment by desrod** [comment]
I'm fine either way; I'm starting to get used to Python, where I have to adhere to the constructs already present in the codebase. If I have a choice, as long as it's consistent across the project, I'm all for using spaces instead of tabs. 

https://www.jwz.org/doc/tabs-vs-spaces.html

**Comment by furlongm** [comment]
I don't mind really, it was more of a "nit" comment. My preference is for tabs but the PR is already approved and should just be merged if there is not a follow-up PR to convert to spaces. Don't want to get into a tabs-vs-spaces debate!

**Pull request closed without merging**
