### PR TITLE
Bump specified erlang version in attributes

### PR DESCRIPTION
**Pull request by kamidzi**
Fixes bloomberg/chef-bcpc#579, albeit quickly

### CODE REVIEW

**Comment by erhudy** [comment]
It looks like this version change needs to be applied across the entire cluster at once, which isn't great:
```
=INFO REPORT==== 19-May-2015::11:01:28 ===
Error description:
   {error,{inconsistent_cluster,"OTP version mismatch: local node is 17.5.3, remote node 17.5"}}

Log files (may contain more information):
   /var/log/rabbitmq/rabbit@ll21-bcpc-r1n2.log
   /var/log/rabbitmq/rabbit@ll21-bcpc-r1n2-sasl.log

Stack trace:
   [{rabbit_mnesia,check_cluster_consistency,0,[]},
    {rabbit,'-boot/0-fun-0-',0,[]},
    {rabbit,start_it,1,[]},
    {init,start_it,1,[]},
    {init,start_em,1,[]}]


=INFO REPORT==== 19-May-2015::11:01:46 ===
Error description:
   {error,{inconsistent_cluster,"OTP version mismatch: local node is 17.5.3, remote node 17.5"}}

Log files (may contain more information):
   /var/log/rabbitmq/rabbit@ll21-bcpc-r1n2.log
   /var/log/rabbitmq/rabbit@ll21-bcpc-r1n2-sasl.log

Stack trace:
   [{rabbit_mnesia,check_cluster_consistency,0,[]},
    {rabbit,'-boot/0-fun-0-',0,[]},
    {rabbit,start_it,1,[]},
    {init,start_it,1,[]},
    {init,start_em,1,[]}]
```

**Comment by erhudy** [comment]
Also it bailed out initially because `apt-get update` hadn't been executed. Maybe this should be solved by having any Chef run always run `apt-get update` at the start of the run?

**Comment by erhudy** [comment]
I think this is okay to merge with the caveat that anyone who needs to upgrade in place will have to conduct a full RabbitMQ cluster shutdown (which shouldn't be a big deal, everything will reconnect).

**Comment by kamidzi** [comment]
In case, maybe we shouldn't be like pivotal; breaking such things across minors. It's early, but we may have been for forced into a minor ver bump...

**Pull request merged**
