### PR TITLE
Backport of MySQL slow query logging and monitoring

### PR DESCRIPTION
**Pull request by kelvk**
Backport of #1140 and #1141 (without Zabbix template changes).

### CODE REVIEW

**Comment by erhudy** [comment]
I need to add a PR to master for turning off slow query logging while doing database backups so that we don't trigger unnecessary alarms. I am testing this PR as is, but I would like to get the backup script change merged to master and then included on this PR as well.

**Comment by kelvk** [comment]
Backport PRs - #1149 and #1150

**Comment by erhudy** [comment]
We seem to be missing the Zabbix template changes.

**Comment by kelvk** [comment]
Intentional. If monitoring (specifically alerting) is desired, upgrade to master/6.x.

**Pull request merged**
