### PR TITLE
Adding the ability to mount the apt mirror via VirtualBox shared folders

### PR DESCRIPTION
**Pull request by erhudy**
This addresses one of the feedback items in #902.

### CODE REVIEW

**Comment by erhudy** [comment]
Since this PR requires another file in the local file cache (VBox guest additions ISO), I added a second commit that will invoke the prereqs script from the environment validator playbook. This can be disabled by setting `update_bcpc_local_cache` to `false` in the group variables.

**Comment by erhudy** [comment]
Functionality added by this ticket is broken by https://www.virtualbox.org/ticket/14683?cversion=0&cnum_hist=34. I am encountering this issue now, not sure why I didn't encounter it initially.

**Comment by kelvk** [comment]
Pushed a bunch of changes make this go. I will re-run from a fresh build tomorrow.

**Comment by kelvk** [comment]
Pushed an update with additional doc change. This has also been tested with another fresh build. Unless anyone wants to review/test as well, I will merge later today.

**Pull request merged**
