### PR TITLE
Fixes #630 - performs Nova DB sync before installing Nova services

### LINKED ISSUE #630: nova-database-sync sometimes fails with a MySQL integrity error
This sometimes happens. Recheffing fixes it.
```
  * bash[nova-database-sync] action run
    
    ================================================================================
    Error executing action `run` on resource 'bash[nova-database-sync]'
    ================================================================================
    
    Mixlib::ShellOut::ShellCommandFailed
    ------------------------------------
    Expected process to exit with [0], but received '1'
    ---- Begin output of "bash"  "/tmp/chef-script20150611-5675-1oqqzwp" ----
    STDOUT: Command failed, please check log for more info
    STDERR: No handlers could be found for logger "oslo_config.cfg"
    2015-06-11 15:24:52.346 19380 CRITICAL nova [-] DBDuplicateEntry: (IntegrityError) (1062, "Duplicate entry 'bcpc-vm1-conductor-0' for key 'uniq_services0host0topic0deleted'") 'ALTER TABLE services ADD CONSTRAINT uniq_services0host0topic0deleted UNIQUE (host, topic, deleted)' ()
    2015-06-11 15:24:52.346 19380 TRACE nova Traceback (most recent call last):
    2015-06-11 15:24:52.346 19380 TRACE nova   File "/usr/bin/nova-manage", line 10, in <module>
    2015-06-11 15:24:52.346 19380 TRACE nova     sys.exit(main())
    2015-06-11 15:24:52.346 19380 TRACE nova   File "/usr/lib/python2.7/dist-packages/nova/cmd/manage.py", line 1382, in main
    2015-06-11 15:24:52.346 19380 TRACE nova     ret = fn(*fn_args, **fn_kwargs)
    2015-06-11 15:24:52.346 19380 TRACE nova   File "/usr/lib/python2.7/dist-packages/nova/cmd/manage.py", line 912, in sync
    2015-06-11 15:24:52.346 19380 TRACE nova     return migration.db_sync(version)
    2015-06-11 15:24:52.346 19380 TRACE nova   File "/usr/lib/python2.7/dist-packages/nova/db/migration.py", line 26, in db_sync
    2015-06-11 15:24:52.346 19380 TRACE nova     return IMPL.db_sync(version=version, database=database)
    2015-06-11 15:24:52.346 19380 TRACE nova   File "/usr/lib/python2.7/dist-packages/nova/db/sqlalchemy/migration.py", line 57, in db_sync
    2015-06-11 15:24:52.346 19380 TRACE nova     version)
    2015-06-11 15:24:52.346 19380 TRACE nova   File "/usr/lib/python2.7/dist-packages/migrate/versioning/api.py", line 186, in upgrade
    2015-06-11 15:24:52.346 19380 TRACE nova     return _migrate(url, repository, version, upgrade=True, err=err, **opts)
    2015-06-11 15:24:52.346 19380 TRACE nova   File "<string>", line 2, in _migrate
    2015-06-11 15:24:52.346 19380 TRACE nova   File "/usr/lib/python2.7/dist-packages/migrate/versioning/util/__init__.py", line 160, in with_engine
    2015-06-11 15:24:52.346 19380 TRACE nova     return f(*a, **kw)
    2015-06-11 15:24:52.346 19380 TRACE nova   File "/usr/lib/python2.7/dist-packages/migrate/versioning/api.py", line 366, in _migrate
    2015-06-11 15:24:52.346 19380 TRACE nova     schema.runchange(ver, change, changeset.step)
    2015-06-11 15:24:52.346 19380 TRACE nova   File "/usr/lib/python2.7/dist-packages/migrate/versioning/schema.py", line 93, in runchange
    2015-06-11 15:24:52.346 19380 TRACE nova     change.run(self.engine, step)
    2015-06-11 15:24:52.346 19380 TRACE nova   File "/usr/lib/python2.7/dist-packages/migrate/versioning/script/py.py", line 148, in run
    2015-06-11 15:24:52.346 19380 TRACE nova     script_func(engine)
    2015-06-11 15:24:52.346 19380 TRACE nova   File "/usr/lib/python2.7/dist-packages/nova/db/sqlalchemy/migrate_repo/versions/216_havana.py", line 1173, in upgrade
    2015-06-11 15:24:52.346 19380 TRACE nova     name='uniq_services0host0topic0deleted').create()
    2015-06-11 15:24:52.346 19380 TRACE nova   File "/usr/lib/python2.7/dist-packages/migrate/changeset/constraint.py", line 44, in create
    2015-06-11 15:24:52.346 19380 TRACE nova     self.__do_imports('constraintgenerator', *a, **kw)
    2015-06-11 15:24:52.346 19380 TRACE nova   File "/usr/lib/python2.7/dist-packages/migrate/changeset/constraint.py", line 32, in __do_imports
    2015-06-11 15:24:52.346 19380 TRACE nova     run_single_visitor(engine, visitorcallable, self, *a, **kw)
    2015-06-11 15:24:52.346 19380 TRACE nova   File "/usr/lib/python2.7/dist-packages/migrate/changeset/databases/visitor.py", line 85, in run_single_visitor
    2015-06-11 15:24:52.346 19380 TRACE nova     fn(element, **kwargs)
    2015-06-11 15:24:52.346 19380 TRACE nova   File "/usr/lib/python2.7/dist-packages/migrate/changeset/ansisql.py", line 294, in visit_migrate_unique_constraint
    2015-06-11 15:24:52.346 19380 TRACE nova     self._visit_constraint(*p, **k)
    2015-06-11 15:24:52.346 19380 TRACE nova   File "/usr/lib/python2.7/dist-packages/migrate/changeset/ansisql.py", line 300, in _visit_constraint
    2015-06-11 15:24:52.346 19380 TRACE nova     self.execute()
    2015-06-11 15:24:52.346 19380 TRACE nova   File "/usr/lib/python2.7/dist-packages/migrate/changeset/ansisql.py", line 44, in execute
    2015-06-11 15:24:52.346 19380 TRACE nova     return self.connection.execute(self.buffer.getvalue())
    2015-06-11 15:24:52.346 19380 TRACE nova   File "/usr/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 721, in execute
    2015-06-11 15:24:52.346 19380 TRACE nova     return self._execute_text(object, multiparams, params)
    2015-06-11 15:24:52.346 19380 TRACE nova   File "/usr/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 870, in _execute_text
    2015-06-11 15:24:52.346 19380 TRACE nova     statement, parameters
    2015-06-11 15:24:52.346 19380 TRACE nova   File "/usr/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 958, in _execute_context
    2015-06-11 15:24:52.346 19380 TRACE nova     context)
    2015-06-11 15:24:52.346 19380 TRACE nova   File "/usr/lib/python2.7/dist-packages/oslo_db/sqlalchemy/compat/handle_error.py", line 261, in _handle_dbapi_exception
    2015-06-11 15:24:52.346 19380 TRACE nova     e, statement, parameters, cursor, context)
    2015-06-11 15:24:52.346 19380 TRACE nova   File "/usr/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 1155, in _handle_dbapi_exception
    2015-06-11 15:24:52.346 19380 TRACE nova     util.raise_from_cause(newraise, exc_info)
    2015-06-11 15:24:52.346 19380 TRACE nova   File "/usr/lib/python2.7/dist-packages/sqlalchemy/util/compat.py", line 199, in raise_from_cause
    2015-06-11 15:24:52.346 19380 TRACE nova     reraise(type(exception), exception, tb=exc_tb)
    2015-06-11 15:24:52.346 19380 TRACE nova   File "/usr/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 951, in _execute_context
    2015-06-11 15:24:52.346 19380 TRACE nova     context)
    2015-06-11 15:24:52.346 19380 TRACE nova   File "/usr/lib/python2.7/dist-packages/sqlalchemy/engine/default.py", line 436, in do_execute
    2015-06-11 15:24:52.346 19380 TRACE nova     cursor.execute(statement, parameters)
    2015-06-11 15:24:52.346 19380 TRACE nova   File "/usr/lib/python2.7/dist-packages/MySQLdb/cursors.py", line 174, in execute
    2015-06-11 15:24:52.346 19380 TRACE nova     self.errorhandler(self, exc, value)
    2015-06-11 15:24:52.346 19380 TRACE nova   File "/usr/lib/python2.7/dist-packages/MySQLdb/connections.py", line 36, in defaulterrorhandler
    2015-06-11 15:24:52.346 19380 TRACE nova     raise errorclass, errorvalue
    2015-06-11 15:24:52.346 19380 TRACE nova DBDuplicateEntry: (IntegrityError) (1062, "Duplicate entry 'bcpc-vm1-conductor-0' for key 'uniq_services0host0topic0deleted'") 'ALTER TABLE services ADD CONSTRAINT uniq_services0host0topic0deleted UNIQUE (host, topic, deleted)' ()
    2015-06-11 15:24:52.346 19380 TRACE nova
    ---- End output of "bash"  "/tmp/chef-script20150611-5675-1oqqzwp" ----
    Ran "bash"  "/tmp/chef-script20150611-5675-1oqqzwp" returned 1
    
    Resource Declaration:
    ---------------------
    # In /var/chef/cache/cookbooks/bcpc/recipes/nova-head.rb
    
     48: bash "nova-database-sync" do
     49:     action :nothing
     50:     user "root"
     51:     code "nova-manage db sync"
     52:     notifies :restart, "service[nova-scheduler]", :immediately
     53:     notifies :restart, "service[nova-cert]", :immediately
     54:     notifies :restart, "service[nova-consoleauth]", :immediately
     55:     notifies :restart, "service[nova-conductor]", :immediately
     56: end
     57: 
    
    Compiled Resource:
    ------------------
    # Declared in /var/chef/cache/cookbooks/bcpc/recipes/nova-head.rb:48:in `from_file'
    
    bash("nova-database-sync") do
      action [:nothing]
      retries 0
      retry_delay 2
      default_guard_interpreter :default
      command "nova-database-sync"
      backup 5
      returns 0
      user "root"
      code "nova-manage db sync"
      interpreter "bash"
      declared_type :bash
      cookbook_name "bcpc"
      recipe_name "nova-head"
    end
```

### PR DESCRIPTION
**Pull request by erhudy**
This fixes #630 by reordering the execution of `nova-manage db sync` to occur before any Nova services are installed.

Because this fixes a race condition, it's not implicitly provable that this actually fixes the problem (theoretically you could build a thousand times and by pure chance not actually encounter the problem), but logically it holds that since the problem could occur when a service started up and began inserting data that would violate a unique constraint, if no Nova services are running, then they won't insert anything that could cause a later application of a unique constraint to fail.

**NOTE**: This only impacts fresh builds; it will have no impact on any clusters that are already built out.

### CODE REVIEW

**Comment by kamidzi** [comment]
Caught the following:
```
* bash[nova-database-sync] action run

    ================================================================================
    Error executing action `run` on resource 'bash[nova-database-sync]'
    ================================================================================

    Mixlib::ShellOut::ShellCommandFailed
    ------------------------------------
    Expected process to exit with [0], but received '1'
    ---- Begin output of "bash"  "/tmp/chef-script20150929-5403-6gnuys" ----
    STDOUT: Command failed, please check log for more info
    STDERR: No handlers could be found for logger "oslo_config.cfg"
    2015-09-29 21:06:45.321 27460 CRITICAL nova [-] DBDuplicateEntry: (IntegrityError) (1062, "Duplicate entry 'bcpc-vm1-conductor-0' for key 'uniq_services0host0topic0deleted'") 'ALTER TABLE services ADD CONSTRAINT uniq_services0host0topic0deleted UNIQUE (host, topic, deleted)' ()
    2015-09-29 21:06:45.321 27460 TRACE nova Traceback (most recent call last):
...
   2015-09-29 21:06:45.321 27460 TRACE nova DBDuplicateEntry: (IntegrityError) (1062, "Duplicate entry 'bcpc-vm1-conductor-0' for key 'uniq_services0host0topic0deleted'") 'ALTER TABLE services ADD CONSTRAINT uniq_services0host0topic0deleted UNIQUE (host, topic, deleted)' ()
    2015-09-29 21:06:45.321 27460 TRACE nova
```

**Comment by erhudy** [comment]
That shouldn't be possible with this, because the database sync is moved to before nova-conductor is installed.

**Comment by kamidzi** [comment]
I should have been more clear - the prior message was a confirmation. That was on a build from master (w/o this patch)

**Comment by kamidzi** [comment]
Builds and chefs into existing cluster.

**Pull request merged**
