### PR TITLE
Increase keystone token cache TTL to 7d.

### LINKED ISSUE #501: Increase Keystone token caching TTL
Spoke offline with @caiush. The suggestion is to raise it to 7d.

### PR DESCRIPTION
**Pull request by kamidzi**
Closes #501

### CODE REVIEW

**Comment by caiush** [comment]
Think you will prob want to up the timeout on horizon, but not sure. Did you test that?

**Comment by kamidzi** [comment]
reply@reply.github.com At: Mar  5 2015 14:42:59" data-digest="From: reply@reply.github.com At: Mar  5 2015 14:42:59" style="">

**Comment by kamidzi** [comment]
Test which part? What's the suspected effect of this timeout on horizon?

**Comment by kamidzi** [comment]
Discussed with @caiush offline and this change should be merged in conjunction with an increase in the Horizon session timeout.

We should just roll the combined changes into the next release.

**Pull request closed without merging**
