### PR TITLE
Fixes #826 - backports patch to fix refreshing security groups

### LINKED ISSUE #826: Changing a security group does not correctly refresh rules for subscribed instances
This traceback occurs in nova-compute.log when an existing security group is edited:
```
2015-09-16 21:04:23.973 18547 ERROR oslo_messaging.rpc.dispatcher [req-098d6981-8348-460d-9fd8-cc7b04504c2c 96d465eb2535443f95e7efcd05276283 a5f9a733bbc6438e83ab79260e37f276 - - -] Exception during message handling: 'metadata'
2015-09-16 21:04:23.973 18547 TRACE oslo_messaging.rpc.dispatcher Traceback (most recent call last):
2015-09-16 21:04:23.973 18547 TRACE oslo_messaging.rpc.dispatcher   File "/usr/lib/python2.7/dist-packages/oslo_messaging/rpc/dispatcher.py", line 142, in _dispatch_and_reply
2015-09-16 21:04:23.973 18547 TRACE oslo_messaging.rpc.dispatcher     executor_callback))
2015-09-16 21:04:23.973 18547 TRACE oslo_messaging.rpc.dispatcher   File "/usr/lib/python2.7/dist-packages/oslo_messaging/rpc/dispatcher.py", line 186, in _dispatch
2015-09-16 21:04:23.973 18547 TRACE oslo_messaging.rpc.dispatcher     executor_callback)
2015-09-16 21:04:23.973 18547 TRACE oslo_messaging.rpc.dispatcher   File "/usr/lib/python2.7/dist-packages/oslo_messaging/rpc/dispatcher.py", line 130, in _do_dispatch
2015-09-16 21:04:23.973 18547 TRACE oslo_messaging.rpc.dispatcher     result = func(ctxt, **new_args)
2015-09-16 21:04:23.973 18547 TRACE oslo_messaging.rpc.dispatcher   File "/usr/lib/python2.7/dist-packages/nova/compute/manager.py", line 6772, in refresh_instance_security_rules
2015-09-16 21:04:23.973 18547 TRACE oslo_messaging.rpc.dispatcher     return self.manager.refresh_instance_security_rules(ctxt, instance)
2015-09-16 21:04:23.973 18547 TRACE oslo_messaging.rpc.dispatcher   File "/usr/lib/python2.7/dist-packages/nova/compute/manager.py", line 434, in decorated_function
2015-09-16 21:04:23.973 18547 TRACE oslo_messaging.rpc.dispatcher     args = (_load_instance(args[0]),) + args[1:]
2015-09-16 21:04:23.973 18547 TRACE oslo_messaging.rpc.dispatcher   File "/usr/lib/python2.7/dist-packages/nova/compute/manager.py", line 425, in _load_instance
2015-09-16 21:04:23.973 18547 TRACE oslo_messaging.rpc.dispatcher     expected_attrs=metas)
2015-09-16 21:04:23.973 18547 TRACE oslo_messaging.rpc.dispatcher   File "/usr/lib/python2.7/dist-packages/nova/objects/instance.py", line 506, in _from_db_object
2015-09-16 21:04:23.973 18547 TRACE oslo_messaging.rpc.dispatcher     instance['metadata'] = utils.instance_meta(db_inst)
2015-09-16 21:04:23.973 18547 TRACE oslo_messaging.rpc.dispatcher   File "/usr/lib/python2.7/dist-packages/nova/utils.py", line 817, in instance_meta
2015-09-16 21:04:23.973 18547 TRACE oslo_messaging.rpc.dispatcher     if isinstance(instance['metadata'], dict):
2015-09-16 21:04:23.973 18547 TRACE oslo_messaging.rpc.dispatcher KeyError: 'metadata'
2015-09-16 21:04:23.973 18547 TRACE oslo_messaging.rpc.dispatcher 
```

### PR DESCRIPTION
**Pull request by erhudy**
Testable by creating a VM and then editing a security group attached to it. Changes will take effect immediately, though because iptables allows RELATED,ESTABLISHED on the Nova filter chain, existing connections/pings will continue to operate when the change takes effect, but new ones will not (so don't be surprised when you delete the ICMP rule while pinging the VM and finding that the ping continues to go after you edit the security group).

### CODE REVIEW

**Comment by erhudy** [comment]
Don't merge this until #816 is merged; this was branched off that in order to take advantage of the patch resource provider. Once #816 was merged, I will rebase this against master to remove the extraneous commit.

**Comment by erhudy** [comment]
I tested this against both 2015.1.0 and 2015.1.1 package sets.

**Comment by erhudy** [comment]
Rebased off master since #822 is merged.

**Comment by kamidzi** [comment]
Indeed, after creating a test VM from bcpc-vm1:
```
+ ssh -ostricthostkeychecking=no -obatchmode=yes -lcirros -i ./id_rsa 192.168.100.129 'nohup nc -l -p 4040 &'
+ nc -w 1 -vz 192.168.100.129 4040
nc: connect to 192.168.100.129 port 4040 (tcp) timed out: Operation now in progress
+ openstack security group rule list default
+----+-------------+-----------+------------+
| ID | IP Protocol | IP Range  | Port Range |
+----+-------------+-----------+------------+
|  1 | icmp        | 0.0.0.0/0 |            |
|  2 | tcp         | 0.0.0.0/0 | 22:22      |
+----+-------------+-----------+------------+
+ openstack security group rule create --proto tcp --dst-port 4040:4040 default
+-----------------+-----------+
| Field           | Value     |
+-----------------+-----------+
| group           | {}        |
| id              | 5         |
| ip_protocol     | tcp       |
| ip_range        | 0.0.0.0/0 |
| parent_group_id | 1         |
| port_range      | 4040:4040 |
+-----------------+-----------+
+ nc -w 1 -vz 192.168.100.129 4040
Connection to 192.168.100.129 4040 port [tcp/*] succeeded!
+ nova secgroup-delete-rule default tcp 4040 4040 0.0.0.0/0
+-------------+-----------+---------+-----------+--------------+
| IP Protocol | From Port | To Port | IP Range  | Source Group |
+-------------+-----------+---------+-----------+--------------+
| tcp         | 4040      | 4040    | 0.0.0.0/0 |              |
+-------------+-----------+---------+-----------+--------------+
+ openstack security group rule list default
+----+-------------+-----------+------------+
| ID | IP Protocol | IP Range  | Port Range |
+----+-------------+-----------+------------+
|  1 | icmp        | 0.0.0.0/0 |            |
|  2 | tcp         | 0.0.0.0/0 | 22:22      |
+----+-------------+-----------+------------+
+ nc -w 1 -vz 192.168.100.129 4040
nc: connect to 192.168.100.129 port 4040 (tcp) timed out: Operation now in progress
```

**Pull request merged**
