### PR TITLE
Hacks in a fix on the trousers postinst script so that it installs

### PR DESCRIPTION
**Pull request by erhudy**
This fixes (I hope) an issue with getting TPM set up on hardware. I regret that this exists.

### CODE REVIEW

**Comment by mihalis68** [comment]
best branch name ever

**Comment by mihalis68** [comment]
I'll test this

**Comment by erhudy** [comment]
Amended to reorder trousers ahead of the other packages, since tpm-tools tries to install it as a dependency.

**Comment by mihalis68** [comment]
This seems to work for me. The only nodes I am having problems with had a failed install before. My fix is this:

```
$ sudo apt-get purge tpm-tools rng-tools
$ sudo chef-client
```
and this works with the above manually merged in and loaded onto my chef server.

**Comment by mihalis68** [comment]
Has now worked on about 25 real machines. Is good.

**Pull request merged**
