### PR TITLE
Raise minimum required OpenStack version to 2015.1.2

### PR DESCRIPTION
**Pull request by erhudy**
- remove patches that were only required by 2015.1.0 or 2015.1.1
- convert remaining patch tasks to bcpc_patch resources

**Merging this PR will make BCPC 5.12.0 the maximum possible version of BCPC that can be installed using OpenStack 2015.1.0 or 2015.1.1.**

The rationale for this PR was to be able to drop a number of older patches that were annoying to maintain and convert all remaining patches to use the `bcpc_patch` resource type.

### Testing
Attempting to rechef using a copy of the Ubuntu cloud archive repo that does not have at least OpenStack 2015.1.2 should result in a failure:
```

* ruby_block[evaluate-version-eligibility] action run

  ================================================================================
  Error executing action `run` on resource 'ruby_block[evaluate-version-eligibility]'
  ================================================================================

  RuntimeError
  ------------
  You must install OpenStack Kilo 2015.1.2 or better. Earlier versions are not supported.

  Cookbook Trace:
  ---------------
  /var/chef/cache/cookbooks/bcpc/recipes/openstack.rb:33:in `block (2 levels) in from_file'
```
(Note that if you wish to test this using our original frozen mirror, you must check out the previous copy of the Ceph release key (from 5.6.0 or earlier) or the convergence run will fail when attempting to install Ceph packages before it gets to the part to be tested.)

Attempting to converge using our current frozen mirror (2015.1.2) or upstream repos (2015.1.3) on fresh builds or over existing builds should be a no-op.

### CODE REVIEW

**Comment by kelvk** [comment]
Existing cluster based on master recheffed without changes as expected. Testing with a fresh build.

**Comment by erhudy** [comment]
I have decided that I am not satisfied with the current canary mechanism that involves installing the python-nova package, both because it's philosophically ugly and because it screws up the in-place upgrade mechanism for Kilo->Liberty I'm working on. I will update this PR with a better mechanism when I have it.

**Comment by erhudy** [comment]
PR updated, did not crush.

**Comment by kelvk** [comment]
All intended patches (both via `bcpc_patch` and new packages) appear in place with fresh cluster build. Re-testing with rechef over an older cluster.

**Comment by kelvk** [comment]
No-op rechef as expected.

**Pull request merged**
