### PR TITLE
Add monitoring for MySQL slow queries

### PR DESCRIPTION
**Pull request by erhudy**

### CODE REVIEW

**Comment by kelvk** [comment]
```
# sudo -u zabbix /usr/local/bin/mysql_slow_query_check.sh 
grep: /var/log/mysql/slow.log: Permission denied
```

Rotated log files (https://github.com/bloomberg/chef-bcpc/blob/master/cookbooks/bcpc/templates/default/logrotate_mysql_slow_query.erb#L4) will need to be group-owned by `adm`.

**Comment by erhudy** [comment]
Changed the logrotate file to create the rotated file as `mysql:adm`. Pushed as an extra commit - if everything checks out I will collapse the commits prior to merge.

Strangely enough, on my local head node where I was repeatedly rotating the logs, everything still appears to be owned by `mysql:adm`, even though I put `mysql:mysql` in the logrotate file and was not aware of the special consideration for Zabbix prior to now. Is there a cron job or something that fixes these permissions regularly?
```
root@bcpc-vm1:/var/log/mysql# ls -l
total 40424
-rw-rw---- 1 mysql adm    14464 Oct 12 14:43 error.log
-rw-rw---- 1 mysql adm 41338620 Oct 14 13:05 slow.log
-rw-rw---- 1 mysql adm      219 Oct 13 12:47 slow.log.1.gz
-rw-rw---- 1 mysql adm      227 Oct 13 12:46 slow.log.2.gz
-rw-rw---- 1 mysql adm      219 Oct 12 17:42 slow.log.3.gz
-rw-rw---- 1 mysql adm    16950 Oct 12 17:27 slow.log.4.gz
```

**Comment by kelvk** [comment]
The commit is good. I don't see the strange behavior on my local build though.

**Comment by erhudy** [comment]
Does this require further attention or should I crush the commits?

**Comment by kelvk** [comment]
Crush and merge.

**Pull request merged**
