### PR TITLE
Add a flag to enable/disable ip rules from permitting VMs talking to APIs

### PR DESCRIPTION
**Pull request by jerenkrantz**
Without this patch, VMs can't talk to the API endpoints on a laptop.

(In a production environment, it is expected that you'd have a fully routable network that has appropriate ACLing to permit VMs to talk to the API endpoints...or not.)

### CODE REVIEW

**Comment by kamidzi** [comment]
Is this also  the case with using virtualbox networking? I am having trouble reproducing access to APIs from within a VM instance.

**Comment by jerenkrantz** [comment]
I was using VMware not VirtualBox.

**Comment by jerenkrantz** [comment]
Can we please merge?

**Comment by erhudy** [comment]
Looks okay to me.

**Comment by mihalis68** [comment]
As I understand this, is a convenience for VMs/laptop builds, and a no-op for production hence I merged it since Justin asked. Sorry for the delay!

**Comment by jerenkrantz** [comment]
Thanks!

**Comment by cbaenziger** [comment]
For reference, I have VM's which talk to the API's extensively; see our chef-bach openstack [branch](https://github.com/cbaenziger/chef-bach/blob/openstack_support/Vagrantfile.openstack#L105-L127) where a VM with Vagrant can orchestrate standing up an entire Hadoop cluster on a BCPC cluster.

**Pull request merged**
