### PR TITLE
Rally Automatic Setup on Bootstrap Node

### PR DESCRIPTION
**Pull request by cloudm2**

### CODE REVIEW

**Comment by kamidzi** [comment]
I'm experiencing the following with unmodified bootstrap vm memory installing packages in the rally recipe:
```
...
dpkg-deb (subprocess): decompressing archive member: lzma error: Cannot allocate memory
dpkg-deb: error: subprocess <decompress> returned error exit status 2
dpkg: error processing archive /var/cache/apt/archives/fonts-dejavu-core_2.34-1ubuntu1_all.deb (--unpack):
 subprocess dpkg-deb --fsys-tarfile returned error exit status 2
No apport report written because the error message indicates an issue on the local system
dpkg-deb (subprocess): decompressing archive member: lzma error: Cannot allocate memory
dpkg-deb: error: subprocess <decompress> returned error exit status 2
dpkg: error processing archive /var/cache/apt/archives/fonts-dejavu-extra_2.34-1ubuntu1_all.deb (--unpack):
 subprocess dpkg-deb --fsys-tarfile returned error exit status 2
No apport report written because the error message indicates an issue on the local system
Errors were encountered while processing:
 /var/cache/apt/archives/fonts-dejavu-core_2.34-1ubuntu1_all.deb
 /var/cache/apt/archives/fonts-dejavu-extra_2.34-1ubuntu1_all.deb
E: Sub-process /usr/bin/dpkg returned an error code (1)
---- End output of apt-get -q -y install default-jre=2:1.7-51 ----
Ran apt-get -q -y install default-jre=2:1.7-51 returned 100
[2015-05-17T16:18:27+00:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)
```

Anyone else experience this?

**Comment by kamidzi** [comment]
@cloudm2, I found that just bumping the memory made it build cleanly. I rebased some of your commits; let me know if you prefer to do this in your own manner... If no objections, I'll merge #571 before Monday?

**Comment by cloudm2** [comment]
I have never seen a memory issue on build. I built it several times yesterday. I have noticed flaky behavior with the new trusty/kilo portion. This could be environmental or something. Replicate by issuing openstack service list and you will get different results each time. Maybe it's memory and I didn't see it.

**Comment by cloudm2** [comment]
The command is:
Openstack service list

Try that after keystone is working and let me know what you see.

**Comment by cloudm2** [comment]
Sorry about the number of comments. The default-jre is the Java runtime for the next piece of jmeter. Rally doesn't use.

**Comment by cloudm2** [comment]
@kamidzi, that's fine and thanks.

**Comment by kamidzi** [comment]
Closed by #571

**Pull request closed without merging**
