### PR TITLE
Fixes #574 - allows amqp_durable_queues control via attribute

### LINKED ISSUE #574: Consider disabling durable queues
With Trusty+Kilo, I saw `nova-conductor` get really confused - with log messages like:

```
2015-05-17 10:21:50.980 9487 INFO oslo_messaging._drivers.impl_rabbit [req-55994053-c547-42a2-97de-35c411c4588e - - - - -] The exchange to reply to reply_73816cf9731c45afa2a7c5fcd57865e6 doesn't exist yet, retrying...
```

I _believe_ that this is related to the fact that some of the RabbitMQ exchanges are per-process - so, when everything is restarted (e.g. cold start), `nova-conductor` still wants those named exchanges to exist and won't process other messages until they are present.  As the exchange names were only for the duration of the process, that particular named exchange will never get created - so `nova-conductor` essentially sits in a deadlock waiting for it.

Ungood.

(I'm wondering if `nova-conductor` is iterating all the queues or exchanges somehow.  I couldn't figure out how `nova-conductor` knew to look for these exchanges.)

We should chat with folks this week in Vancouver, but `nova-conductor` was way happier with handling service restarts when durability was turned off.  It could successfully come back from a cold start in my testing with durability disabled.

### PR DESCRIPTION
**Pull request by erhudy**
This fixes issue #574.

### CODE REVIEW

**Comment by jerenkrantz** [comment]
LGTM.  We'll ask around this week to get feedback to see if others recommend running with durable queues or not.

**Comment by erhudy** [comment]
Okay, will keep this one not merged.

**Comment by kamidzi** [comment]
Closing for now to disambiguate.

**Comment by erhudy** [comment]
Reopened after revising the attributes file to not change the current configuration of durable queues.

**Comment by erhudy** [comment]
Testing against existing cluster.

**Comment by erhudy** [comment]
Works fine with existing cluster.

**Pull request merged**
