### PR TITLE
Move openstack security policies to separate files

### PR DESCRIPTION
**Pull request by semenovroman**
This makes it easier to work with default attributes. I would also move couple other things, like ceph and monitoring, to separate files. Thoughts?

### CODE REVIEW

**Comment by kamidzi** [comment]
All for it.

**Comment by erhudy** [comment]
double plus thumbs up

**Comment by mihalis68** [comment]
And my axe

**Comment by erhudy** [comment]
Tested and compared to output of a master build, everything looks the same as expected. Please rebase against master when able and then I will merge.

**Comment by semenovroman** [comment]
Looks like this PR did not survive branch deletion on my repo. I submitted a new PR.

**Pull request closed without merging**
