### PR TITLE
Make dns_fill.py compliant with Keystone v3

### PR DESCRIPTION
**Pull request by kelvk**
This fixes instance CNAME creation on Liberty.

### CODE REVIEW

**Comment by erhudy** [comment]
Cherry-picked this onto stable-5.x to verify v2.0 compatibility and this happened after updating:
```
vagrant@bcpc-vm1:~$ sudo /usr/local/bin/dns_fill.py -c /usr/local/etc/dns_fill.yml dump
Traceback (most recent call last):
  File "/usr/local/bin/dns_fill.py", line 235, in <module>
    args.func(args)
  File "/usr/local/bin/dns_fill.py", line 208, in c_dump
    dnsp = dns_popper(config)
  File "/usr/local/bin/dns_fill.py", line 30, in __init__
    auth_params['tenant_name'] = config['OS_PROJECT_NAME']
KeyError: 'OS_PROJECT_NAME'
```

It looks like `/usr/local/etc/dns_fill.yml` still has `OS_TENANT_NAME` as the key instead of `OS_PROJECT_NAME`.

**Comment by kelvk** [comment]
Pushed updated config key.

**Comment by erhudy** [comment]
Fixed for stable-5.x, testing on master with Liberty now.

**Comment by erhudy** [comment]
Checks out on master. Got expected traceback before fix:
```
Traceback (most recent call last):
  File "/usr/local/bin/dns_fill.py", line 227, in <module>
    args.func(args)
  File "/usr/local/bin/dns_fill.py", line 192, in c_run
    nova_rows = dnsp.generate_records_from_vms()
  File "/usr/local/bin/dns_fill.py", line 68, in generate_records_from_vms
    "Non-existent project %s: " % tid +
NameError: global name 'tid' is not defined
```

After applying fix, `dns_fill.py dump` and `dns_fill.py run` both work as expected.

**Pull request merged**
