### PR TITLE
Add issues_url and source_url to bcpc cookbook metadata

### PR DESCRIPTION
**Pull request by erhudy**
Super softball PR that adds `issues_url` and `source_url` to satisfy foodcritic.

### CODE REVIEW

**Comment by erhudy** [comment]
Resolves #490. (I think.)

**Comment by kamidzi** [comment]
It appears there are some missing dependencies in the new metadata, especially those used by the Basic role. Is this intentional?

**Comment by erhudy** [comment]
The dependency metadata looks out of date. I will update it to synchronize it with the current dependency cookbook versions.

**Comment by erhudy** [comment]
Rebased to repair merge conflict.

**Pull request closed without merging**
