### PR TITLE
Two CephX changes: Cinder/Glance CephX clients and perms on admin sockets

### LINKED ISSUE #652: Ceph commands now require sudo
On a cluster member ceph -s reports

```
ubuntu@bcpc-vm1:~$ ceph -s
2015-06-17 19:30:16.929600 7feb30b4a700 -1 asok(0x7feb28000bf0) AdminSocketConfigObs::init: failed: AdminSocket::bind_and_listen: failed to bind the UNIX domain socket to '/var/run/ceph/ceph-client.admin.24059.140647965134048.asok': (13) Permission denied
```

### PR DESCRIPTION
**Pull request by caiush**
This PR does two things:
* Previously we were using the admin key for every ceph operation. This key has the following perms:
```
	caps mds = "allow"
	caps mon = "allow *"
	caps osd = "allow *"
```
For various security reasons this seems like a bad idea. In a future PR I will remove the admin key from the compute nodes. However, there may be monitoring consequences as you will be unable to do things like `ceph health` without passing your own key. If indeed this is a problem we can create a readonly key for mons. Monitoring should however be able to get everything it needs through the admin sockets.  @kelvk will have to comment.
* Secondly, ceph was configured to create an admin socket for *all* ceph clients. This includes the admin client (which *should* just be used to do admin tasks on the cluster, see above). Now we break down the configuration of the clients based on type. So cinder and glance clients create sockets, but things like `ceph health` does not. I found that this functionality was actually broken for any of the useful clients anyhow. So we weren't even creating admin sockets for cinder clients (no matter which cephx client they use). This is a simple fix to apparmor config.  Fixes #652 

This should be able to be cheff-ed in to an already running BCPC cluster, perhaps bouncing openstack services will be required.

### CODE REVIEW

**Comment by kelvk** [comment]
I am not particularly worried even if it breaks monitoring on compute nodes, since having ceph-related checks run on head nodes should suffice. I will test this in any case.

**Comment by erhudy** [comment]
I was able to chef this in and run `ceph` commands. However, attempting to create a volume through Cinder dies a horrible death:
```
2015-07-21 00:43:11.223 8548 TRACE oslo_messaging.rpc.dispatcher Traceback (most recent call last):
2015-07-21 00:43:11.223 8548 TRACE oslo_messaging.rpc.dispatcher   File "/usr/lib/python2.7/dist-packages/oslo_messaging/rpc/dispatcher.py", line 142, in _dispatch_and_reply
2015-07-21 00:43:11.223 8548 TRACE oslo_messaging.rpc.dispatcher     executor_callback))
2015-07-21 00:43:11.223 8548 TRACE oslo_messaging.rpc.dispatcher   File "/usr/lib/python2.7/dist-packages/oslo_messaging/rpc/dispatcher.py", line 186, in _dispatch
2015-07-21 00:43:11.223 8548 TRACE oslo_messaging.rpc.dispatcher     executor_callback)
2015-07-21 00:43:11.223 8548 TRACE oslo_messaging.rpc.dispatcher   File "/usr/lib/python2.7/dist-packages/oslo_messaging/rpc/dispatcher.py", line 130, in _do_dispatch
2015-07-21 00:43:11.223 8548 TRACE oslo_messaging.rpc.dispatcher     result = func(ctxt, **new_args)
2015-07-21 00:43:11.223 8548 TRACE oslo_messaging.rpc.dispatcher   File "/usr/lib/python2.7/dist-packages/osprofiler/profiler.py", line 105, in wrapper
2015-07-21 00:43:11.223 8548 TRACE oslo_messaging.rpc.dispatcher     return f(*args, **kwargs)
2015-07-21 00:43:11.223 8548 TRACE oslo_messaging.rpc.dispatcher   File "/usr/lib/python2.7/dist-packages/cinder/volume/manager.py", line 468, in create_volume
2015-07-21 00:43:11.223 8548 TRACE oslo_messaging.rpc.dispatcher     _run_flow()
2015-07-21 00:43:11.223 8548 TRACE oslo_messaging.rpc.dispatcher   File "/usr/lib/python2.7/dist-packages/cinder/volume/manager.py", line 456, in _run_flow
2015-07-21 00:43:11.223 8548 TRACE oslo_messaging.rpc.dispatcher     flow_engine.run()
2015-07-21 00:43:11.223 8548 TRACE oslo_messaging.rpc.dispatcher   File "/usr/lib/python2.7/dist-packages/taskflow/engines/action_engine/engine.py", line 96, in run
2015-07-21 00:43:11.223 8548 TRACE oslo_messaging.rpc.dispatcher     for _state in self.run_iter():
2015-07-21 00:43:11.223 8548 TRACE oslo_messaging.rpc.dispatcher   File "/usr/lib/python2.7/dist-packages/taskflow/engines/action_engine/engine.py", line 153, in run_iter
2015-07-21 00:43:11.223 8548 TRACE oslo_messaging.rpc.dispatcher     failure.Failure.reraise_if_any(failures.values())
2015-07-21 00:43:11.223 8548 TRACE oslo_messaging.rpc.dispatcher   File "/usr/lib/python2.7/dist-packages/taskflow/types/failure.py", line 244, in reraise_if_any
2015-07-21 00:43:11.223 8548 TRACE oslo_messaging.rpc.dispatcher     failures[0].reraise()
2015-07-21 00:43:11.223 8548 TRACE oslo_messaging.rpc.dispatcher   File "/usr/lib/python2.7/dist-packages/taskflow/types/failure.py", line 251, in reraise
2015-07-21 00:43:11.223 8548 TRACE oslo_messaging.rpc.dispatcher     six.reraise(*self._exc_info)
2015-07-21 00:43:11.223 8548 TRACE oslo_messaging.rpc.dispatcher   File "/usr/lib/python2.7/dist-packages/taskflow/engines/action_engine/executor.py", line 67, in _execute_task
2015-07-21 00:43:11.223 8548 TRACE oslo_messaging.rpc.dispatcher     result = task.execute(**arguments)
2015-07-21 00:43:11.223 8548 TRACE oslo_messaging.rpc.dispatcher   File "/usr/lib/python2.7/dist-packages/cinder/volume/flows/manager/create_volume.py", line 639, in execute
2015-07-21 00:43:11.223 8548 TRACE oslo_messaging.rpc.dispatcher     **volume_spec)
2015-07-21 00:43:11.223 8548 TRACE oslo_messaging.rpc.dispatcher   File "/usr/lib/python2.7/dist-packages/cinder/volume/flows/manager/create_volume.py", line 613, in _create_raw_volume
2015-07-21 00:43:11.223 8548 TRACE oslo_messaging.rpc.dispatcher     return self.driver.create_volume(volume_ref)
2015-07-21 00:43:11.223 8548 TRACE oslo_messaging.rpc.dispatcher   File "/usr/lib/python2.7/dist-packages/osprofiler/profiler.py", line 105, in wrapper
2015-07-21 00:43:11.223 8548 TRACE oslo_messaging.rpc.dispatcher     return f(*args, **kwargs)
2015-07-21 00:43:11.223 8548 TRACE oslo_messaging.rpc.dispatcher   File "/usr/lib/python2.7/dist-packages/cinder/volume/drivers/rbd.py", line 524, in create_volume
2015-07-21 00:43:11.223 8548 TRACE oslo_messaging.rpc.dispatcher     features=client.features)
2015-07-21 00:43:11.223 8548 TRACE oslo_messaging.rpc.dispatcher   File "/usr/lib/python2.7/dist-packages/rbd.py", line 222, in create
2015-07-21 00:43:11.223 8548 TRACE oslo_messaging.rpc.dispatcher     raise make_ex(ret, 'error creating image')
2015-07-21 00:43:11.223 8548 TRACE oslo_messaging.rpc.dispatcher PermissionError: error creating image
2015-07-21 00:43:11.223 8548 TRACE oslo_messaging.rpc.dispatcher 
```

**Comment by erhudy** [comment]
(I did restart OpenStack services on all nodes prior to trying to do anything with Cinder.)

**Comment by caiush** [comment]
whoops, quite right, the volumes pool was incorrectly named in ceph auth caps for cinder. fixed.

**Comment by caiush** [comment]
Note, that to get that bugfix, you need to either rebuild or:
```
root@bcpc-vm1:/home/vagrant# ceph auth caps client.cinder   mon 'allow r' osd 'allow class-read object_prefix rbd_children, allow rwx pool=volumes-ssd,allow rwx pool=volumes-hdd, allow rwx pool=vms, allow rx pool=images'
updated caps for client.cinder
```

**Comment by erhudy** [comment]
I'll give it another go tomorrow morning.

**Comment by erhudy** [comment]
Rebuilt and volumes seem fine now; able to create, attach and detach.

**Comment by kelvk** [comment]
LGTM. I am not seeing any more permissions errors in Zabbix agent log.

**Comment by erhudy** [comment]
+1

**Pull request merged**
