### PR TITLE
add screen recipe

### PR DESCRIPTION
**Pull request by furlongm**
Installs screen and adds a basic configuration file

### CODE REVIEW

**Comment by srsakhamuri** [comment]
Good idea.

Just a thought, shall we keep these auxiliary recipes into their own cookbook, without adding to bcpc cookbook. Rally etc also will be moved to this new cookbook.

**Comment by kamidzi** [comment]
Agree with @srsakhamuri on separate cookbook in this case.

**Comment by furlongm** [comment]
Some of the current PRs (kexec, etckeeper) are very useful to have from the very beginning of the chef-bcpc build (especially with vagrant).

Two questions:

1) To clarify, you mean another cookbook within chef-bcpc?
2) What are the benefits of moving to another cookbook vs remaining in the bcpc cookbook?

**Comment by kamidzi** [comment]
1. Doesn't really matter, just not the bcpc cookbook.
2. The bcpc cookbook is currently bloated and is/has been a nightmare to maintain. Decomposing grants options for the future.

**Pull request merged**
