### PR TITLE
Parameterize Java options for Elasticsearch

### PR DESCRIPTION
**Pull request by kelvk**
Garbage collection logging will be enabled by default. No change to default heap size (256m).

### CODE REVIEW

**Comment by erhudy** [comment]
Is 256MB enough heap size for Elasticsearch to do anything useful? In my experience it requires considerable amounts of memory.

**Comment by kelvk** [comment]
The value will almost certainly be overridden in production deployments (bare-metal). I am only keeping it low by default for local virtual environments.

**Comment by erhudy** [comment]
Testing.

**Comment by erhudy** [comment]
Looks fine to me.

**Pull request merged**
