### PR TITLE
Forward-port missing features from 4.0.0 release

### PR DESCRIPTION
**Pull request by kamidzi**
After unstable/trusty diverged into release-4.x and unstable/trusty_and_kilo -> release-5.x, development continued on 4.x series. Some features should be forward-ported. (Incidently, github GUI did not allow me to compare against _tag_ 4.0.0 ...)

### CODE REVIEW

**Comment by erhudy** [comment]
Since this will need rebasing/manual merging, I would like to keep the exclusions for IntelliJ files in `chefignore`, because it has a bad habit of blasting .iml stuff all over the place.

**Comment by kamidzi** [comment]
Right, its unfortunate about chefignore. It's been causing conflicts everywhere...

**Comment by erhudy** [comment]
I merged this onto detached master, resolving the `chefignore` conflict in the following way. Testing against existing cluster.
```
# Put files/directories that should be ignored in this file.
# Lines that start with '# ' are comments.

# emacs
*~

# vim
*.sw[a-z]

# IntelliJ
*.iml
.idea/

#cookbooks/bcpc/files/default/bins/**
*chef-*.deb
*.box
*.vdi
```

**Comment by erhudy** [comment]
No changes for an existing cluster aside from the changes to `chefignore`, I probably should've actually looked at the changes.

**Pull request merged**
