### PR TITLE
Extract configfile loading to common functions

### PR DESCRIPTION
**Pull request by kamidzi**
This should allow running `shared_prereqs.sh` independently when behind a proxy.

### CODE REVIEW

**Comment by erhudy** [comment]
The changes seem to now expect that `BOOTSTRAP_HTTP_PROXY` and `BOOTSTRAP_HTTPS_PROXY` will always be set. When running on a system not behind proxy servers which do not have these variables configured:
```
BCPC Vagrant BootstrapV2 0.2
--------------------------------------------
Bootstrapping local Vagrant environment...
Performing preflight environment validation...
Checking VirtualBox and Vagrant...
Downloading necessary files to local cache...
Environment variable BOOTSTRAP_HTTP_PROXY must be set!
Environment variable BOOTSTRAP_HTTPS_PROXY must be set!
Environment variable BOOTSTRAP_HTTPS_PROXY must be set!
```

**Comment by kamidzi** [comment]
Moved the guard, should fix that issue. Though is someone were to want to add another step to the bootstrap process before the prereq fetching that requires proxy configuration, she'd have to be...aware.  Force-pushed the change.

**Comment by erhudy** [comment]
Is the goal that `shared_prereqs.sh` should be executable as a standalone script without being called from `BOOT_GO.sh`? If I try to run `shared_prereqs.sh` by itself (e.g. via `bootstrap/shared/shared_prereqs.sh`), it fails thusly:
```
➜  chef-bcpc git:(f609d15) bootstrap/shared/shared_prereqs.sh 
bootstrap/shared/shared_prereqs.sh: line 11: check_for_envvars: command not found
```

**Comment by erhudy** [comment]
To be clear, I don't think that's a regression; there's always been ordering issues with these scripts and making them standalone, hence wrapping it all in `BOOT_GO.sh` to handle those issues. Since `shared_prereqs.sh` is exceptional among these scripts in that it has a valid reason to be executed standalone, maybe we should intentionally duplicate any functions into it as needed so that it can run by itself?

**Comment by kamidzi** [comment]
Yeah, that may be a more reasonable approach. I'll re-work this in another PR

**Comment by kamidzi** [comment]
Actually, come to think of it - My original intention was to simply make the invocation work as documented in the anisble build guides, for example https://github.com/bloomberg/chef-bcpc/blob/master/docs/ansible_local_build_guide.md

**Comment by kamidzi** [comment]
How about we just merge just as a temporary measure, since this behavior is already documented?

**Comment by erhudy** [comment]
Fine with me, it's not breaking anything that isn't already broken. I will verify.

**Comment by erhudy** [comment]
Trashed `~/.bcpc-cache` and re-ran everything via `BOOT_GO.sh` on both a system with direct Internet access and a system using a proxy server. Everything seems to work as expected.

**Pull request merged**
