### PR TITLE
install apache2-utils (required for mitaka)

### PR DESCRIPTION
**Pull request by furlongm**

### CODE REVIEW

**Comment by mihalis68** [comment]
this just adds tools, very unlikely to actively meddle in existing chef-bcc infra, and I understand is actually required in mitaka.

**Comment by furlongm** [comment]
apache2 doesn't start without this package after the upgrade, so the chef run fails.

**Comment by kamidzi** [comment]
I don't think is a dangerous change, but I haven't found that it *is* necessary for mitaka

```
# curl -s http://$(getent hosts $(uname -n) | awk '{print $NF}') | grep mitaka && apt-cache policy apache2-utils
                <p class="version">BCPC cookbook 7.0.0 (mitaka-updates)</p>
apache2-utils:
  Installed: (none)
  Candidate: 2.4.7-1ubuntu4.18
  Version table:
     2.4.7-1ubuntu4.18 0
        500 http://xx.xx.96.11/ubuntu/ trusty-updates/main amd64 Packages
        500 http://xx.xx.96.11/ubuntu/ trusty-security/main amd64 Packages
     2.4.7-1ubuntu4 0
        500 http://xx.xx.96.11/ubuntu/ trusty/main amd64 Packages
```

**Comment by furlongm** [comment]
@kamidzi on my clean upgrade from 6.4.3 to 7.0.0 it caused chef to fail as apache2 failed to (re)start

**Comment by furlongm** [comment]
On a freshly-installed baremetal node running 6.4.3:

```
# service apache2 start
 * Starting web server apache2
 * 
env: htcacheclean: No such file or directory

# apt-get install apache2-utils -y
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following NEW packages will be installed:
  apache2-utils
0 upgraded, 1 newly installed, 0 to remove and 7 not upgraded.
Need to get 82.2 kB of archives.
After this operation, 347 kB of additional disk space will be used.
Get:1 http://100.76.80.11/ubuntu/ trusty-updates/main apache2-utils amd64 2.4.7-1ubuntu4.13 [82.2 kB]
Fetched 82.2 kB in 0s (4,247 kB/s)       
Selecting previously unselected package apache2-utils.
(Reading database ... 89529 files and directories currently installed.)
Preparing to unpack .../apache2-utils_2.4.7-1ubuntu4.13_amd64.deb ...
Unpacking apache2-utils (2.4.7-1ubuntu4.13) ...
Processing triggers for man-db (2.6.7.1-1ubuntu1) ...
Setting up apache2-utils (2.4.7-1ubuntu4.13) ...

# service apache2 start
 * Starting web server apache2
#
```

**Pull request merged**
