### PR TITLE
Upgrade to Calico 3.27.0 - RDTIBCC-4947

### PR DESCRIPTION
**Pull request by comay**
I've tested the upgrade under both a `3h3w` build as well as through a Jenkins build including a full Rally run. All builds were successful and the tests passed.

### CODE REVIEW

**Comment by tj90241** [comment]
What testing was performed?

**Comment by tj90241** [comment]
This hack should now be removed:
https://github.com/bloomberg/chef-bcpc/commit/c65a83040ed104a754c8351e534de1095d45e289#diff-608b0148f775df0cd6f1a88372206290443a13677cb8c5db5a981fbdea256a0eR189

The fixes for the BPF objects are contained within 3.27.0 per our request.

**Comment by comay** [comment]
> This hack should now be removed: [c65a830#diff-608b0148f775df0cd6f1a88372206290443a13677cb8c5db5a981fbdea256a0eR189](https://github.com/bloomberg/chef-bcpc/commit/c65a83040ed104a754c8351e534de1095d45e289#diff-608b0148f775df0cd6f1a88372206290443a13677cb8c5db5a981fbdea256a0eR189)
> 
> The fixes for the BPF objects are contained within 3.27.0 per our request.

Fixed.

**Comment by comay** [comment]
> What (functional) testing was performed? The virtual clusters do not have policy pushed to them...?

As I typically do, I created a number of instances and verified that the policy set by the default security groups is enacted by Calico. I will definitely test this on a semi-production system prior to merging, once the packages are available internally (PR already approved but not yet merged or deployed for that). In any case, I wasn't going to merge this until it's available internally.

Also, I think perhaps it makes sense to provide some sample policy that mirrors what the security groups provides (such as ICMP and/or SSH) that can be used to model Calico in production better but I think that's the subject of a separate PR.

**Review by tj90241 — APPROVED** [review]
As long as representative policy set is tested, ok -- that's my primary concern here... given the nature of Calico 3.27 was to optimize many of the former algorithms related to Felix policy, there could be a regression in the policy rendering that would not be seen in just a vanilla build (as you mention).

**Pull request merged**
