### PR TITLE
Add fallback firewall rule for out-of-cluster Zabbix-agent communication

### PR DESCRIPTION
**Pull request by kelvk**
This creates a rule to permit inbound Zabbix-agent connectivity. This is necessary for nodes monitored by a VIP that lives outside of its management subnet.

### CODE REVIEW

**Comment by erhudy** [comment]
The expectation is that the IP address of the external Zabbix would be in `["bcpc"]["management"]["monitoring"]["vip"]`?

**Comment by kelvk** [comment]
It is. I think I will change the attribute `['bcpc']['monitoring']['vip']` since external cluster monitoring will likely be the primary/only use case in future. Hold off review until I push a new update.

**Comment by kelvk** [comment]
Commit updated.

**Comment by erhudy** [comment]
One suggestion: if `["bcpc"]["management"]["monitoring"]["vip"]` is set and ["bcpc"]["monitoring"]["vip"]` is not, intentionally fail the Chef run so that the user becomes aware of the need to change the environment file.

**Comment by erhudy** [comment]
Rebuilt and it seems to work as expected - new firewall rules are in place on the work nodes and monitoring nodes, Zabbix checks are working.

**Comment by erhudy** [comment]
Retesting with additional change and will merge if all is well.

**Comment by kelvk** [comment]
Hmm, in-line comments don't seem to generate email notifications. Anyway, I've updated commit with fix.

**Comment by erhudy** [comment]
It caught the error this time. Going to test cheffing on an existing cluster and will merge if good.

**Comment by erhudy** [comment]
Tested on existing cluster with success.

**Pull request merged**
