### PR TITLE
Make ProxySQL user updates more reliable

### PR DESCRIPTION
**Pull request by mboruta1**
Previously a flag was set in the ProxySQL recipe when user attributes
needed to be updated, and read by subsequent recipes. This would require
a full chef run be completed every time a user attribute was changed,
otherwise subsequent chef runs would not have the said flag set. This
change makes it so that each recipe checks whether its ProxySQL user
needs to be updated.

Signed-off-by: Mike Boruta <mboruta1@bloomberg.net>

*Issue number of the reported bug or feature request: #<number>*

**Describe your changes**
A clear and concise description of the changes you have made.

**Testing performed**
Describe the testing you have performed to ensure that the bug has been addressed, or that the new feature works as planned.

**Additional context**
Add any other context about your contribution here.

### CODE REVIEW

**Review by tj90241 — CHANGES_REQUESTED** [review]
The `vars-user.erb` file can be deleted now from this repository right?
Likewise, should we delete it from the filesystem(s) now that it's no longer referenced?

**Comment by mboruta1** [comment]
Thank you Tyler for your review! Indeed we should delete vars-users from the repo; I also added a step at the top of the recipe to delete said file if present along with a note to remove said chef resource in the future once enough time has passed. Lastly, I added the `server_version` variable to the ProxySQL configuration file and attributes.

**Review by tj90241 — APPROVED** [review]
Thanks - looks great! 🎉

**Review by comay — APPROVED** [review]
Looks good - just a nit that you're very consistent using the proper noun ProxySQL but we should afford the same in the comments for the name MySQL. 😉

**Comment by mboruta1** [comment]
Thank you David, updated all occurrences of `mysql` and `proxysql` in comments across the project accordingly :).

**Review by justinjpacheco — APPROVED** [review]

**Pull request merged**
