### PR TITLE
Switch to using fqdn endpoints

### PR DESCRIPTION
**Pull request by semenovroman**
This PR makes keystone list API endpoints using fqdn instead of ip addresses (makes ssl setup significantly cleaner).

### CODE REVIEW

**Comment by erhudy** [comment]
Have you tried to see whether this works when doing a local cluster build?

**Comment by semenovroman** [comment]
So far I just tried re-chefing, will be rebuilding from scratch in couple hours.

**Comment by mihalis68** [comment]
This depends on https://github.com/bloomberg/chef-bcpc/issues/683 which is marked as an enhancement but I'd call a bug. So I would prefer not to merge this until 683 is resolved.

**Comment by erhudy** [comment]
I suspect this will not work as is for local builds because it will require a hostfile entry for `openstack.#{node['bcpc']['hypervisor_domain']}` to be added to `/etc/hosts`, since we're fudging DNS locally. It should probably be added in any event since API calls are so frequent and would save occasional trips out to DNS.

**Comment by erhudy** [comment]
Tagging **Do not merge** until the cluster/hypervisor domain split is complete.

**Comment by semenovroman** [comment]
@erhudy you are right, it does not work without `/etc/hosts` entry. Works fine with the entry (https://github.com/semenovroman/chef-bcpc/commit/e9eecd47258ee2ff67f42626b52dd1b0c0fd73f8)

**Comment by semenovroman** [comment]
Updated PR to use 'cluster_domain'\'hypervisor_domain'.

**Comment by semenovroman** [comment]
Closing this one, will create a new one based on newer master.

**Pull request closed without merging**
