### PR TITLE
Cpufreq scaling governor control

### PR DESCRIPTION
**Pull request by erhudy**
This PR is difficult to test because the vCPUs in VirtualBox do not have cpufreq enabled, and thusly the recipe just skips over them. I tested each part in isolation on my desktop outside of Chef and verified that the behavior is as intended (it reads the current and available governors correctly and writes the requested governor mode out).

### CODE REVIEW

**Comment by erhudy** [comment]
This is a followup to #529 (which should also be merged).

**Comment by jerenkrantz** [comment]
If we are going to depend upon this (which is likely a good thing), we
should probably move the installation of the packages to this recipe rather
than the debugging package.

**Comment by erhudy** [comment]
Do you want me to incorporate #529 into this commit and close that PR?

**Comment by jerenkrantz** [comment]
Fine by me!

**Comment by erhudy** [comment]
I validated the behavior of this provider on Trusty (the layout of `/sys/devices/system/cpu` is identical on Precise, so it should function identically there), testing different CPU governor types and also invalid governor types to ensure that Chef would properly bail out.

**Comment by kkoh61** [comment]
Tested OK on Precise. Merging.

**Pull request merged**
