### PR TITLE
Parameterize innodb_buffer_pool_size and innodb_buffer_pool_instances

### PR DESCRIPTION
**Pull request by erhudy**

### CODE REVIEW

**Comment by erhudy** [comment]
https://dev.mysql.com/doc/refman/5.6/en/innodb-multiple-buffer-pools.html for information on configuring multiple buffer pools (not that there is enough memory by default on a local build)

**Comment by kelvk** [comment]
This will break #711.

**Comment by erhudy** [comment]
Oh, sorry, I did not remember to update the MySQL monitoring configuration. I will do that now.

**Comment by erhudy** [comment]
I re-parameterized them as template variables and defined the default values explicitly for the monitoring setup as well.

**Comment by kelvk** [comment]
Note that this change will restart MySQL instances even with default innodb parameters. I don't particularly feel that will be a problem as long as we perform a rolling restart.

**Pull request merged**
