### PR TITLE
Force ifup in case of missing dhclient during vm provision

### LINKED ISSUE #1305: reconfigure-eth0-on-vms.sh provisioner can fail on re-provisions
If the vms have been halted for some reason and are re-provisioned while being brought up, it is possible that `dhclient` is not running, failing the operation as per the following:

```
$ vagrant up
Bringing machine 'bootstrap' up with 'virtualbox' provider...
Bringing machine 'r1n1' up with 'virtualbox' provider...
Bringing machine 'r1n2' up with 'virtualbox' provider...
==> bootstrap: Clearing any previously set forwarded ports...
==> bootstrap: Clearing any previously set network interfaces...
==> bootstrap: Preparing network interfaces based on configuration...
    bootstrap: Adapter 1: nat
    bootstrap: Adapter 2: intnet
    bootstrap: Adapter 3: intnet
    bootstrap: Adapter 4: intnet
==> bootstrap: Forwarding ports...
    bootstrap: 22 (guest) => 2222 (host) (adapter 1)
==> bootstrap: Running 'pre-boot' VM customizations...
==> bootstrap: Booting VM...
==> bootstrap: Waiting for machine to boot. This may take a few minutes...
    bootstrap: SSH address: 127.0.0.1:2222
    bootstrap: SSH username: vagrant
    bootstrap: SSH auth method: private key
==> bootstrap: Machine booted and ready!
==> bootstrap: Checking for guest additions in VM...
    bootstrap: The guest additions on this VM do not match the installed version of
    bootstrap: VirtualBox! In most cases this is fine, but in rare cases it can
    bootstrap: prevent things such as shared folders from working properly. If you see
    bootstrap: shared folder errors, please make sure the guest additions within the
    bootstrap: virtual machine match the version of VirtualBox you have installed on
    bootstrap: your host and reload your VM.
    bootstrap:
    bootstrap: Guest Additions Version: 4.3.36
    bootstrap: VirtualBox Version: 5.1
==> bootstrap: Setting hostname...
==> bootstrap: Configuring and enabling network interfaces...
==> bootstrap: Mounting shared folders...
    bootstrap: /chef-bcpc-host => /Users/kmidzi/build/chef-bcpc
    bootstrap: /chef-bcpc-files => /Users/kmidzi/.bcpc-cache
==> bootstrap: Machine already provisioned. Run `vagrant provision` or use the `--provision`
==> bootstrap: flag to force provisioning. Provisioners marked to run always will still run.
==> bootstrap: Running provisioner: delete-default-gw-on-eth0 (shell)...
    bootstrap: Running: /var/folders/2d/nj6nk1zn6f15y6zd4kz6qjk40000gp/T/vagrant-shell20171120-5455-vhc2rn.sh
==> bootstrap: dhclient: no process found
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.
```

### PR DESCRIPTION
**Pull request by kamidzi**
Fixes #1305.

After the fix, provision succeeds:

```
$ vagrant up
Bringing machine 'bootstrap' up with 'virtualbox' provider...
Bringing machine 'r1n1' up with 'virtualbox' provider...
Bringing machine 'r1n2' up with 'virtualbox' provider...
==> bootstrap: Machine already provisioned. Run `vagrant provision` or use the `--provision`
==> bootstrap: flag to force provisioning. Provisioners marked to run always will still run.
==> bootstrap: Running provisioner: delete-default-gw-on-eth0 (shell)...
    bootstrap: Running: /var/folders/2d/nj6nk1zn6f15y6zd4kz6qjk40000gp/T/vagrant-shell20171120-6404-1k8fyq0.sh
==> bootstrap: Running provisioner: add-default-gw (shell)...
    bootstrap: Running: inline script
<...>
==> r1n1: Machine already provisioned. Run `vagrant provision` or use the `--provision`
==> r1n1: flag to force provisioning. Provisioners marked to run always will still run.
==> r1n1: Running provisioner: delete-default-gw-on-eth0 (shell)...
    r1n1: Running: /var/folders/2d/nj6nk1zn6f15y6zd4kz6qjk40000gp/T/vagrant-shell20171120-6404-84fqb9.sh
==> r1n1: RTNETLINK answers: No such file or directory
==> r1n1: RTNETLINK answers: No such process
==> r1n1: RTNETLINK answers: No such process
==> r1n1: Running provisioner: add-default-gw (shell)...
    r1n1: Running: inline script
```

It can be seen that default gateway is indeed added as specified:
```
$ cat ../config/singlehead.json
{
  "cluster_name": "Test-Laptop-Vagrant",
  "nodes": {
    "bcpc-dev-bootstrap": {
      "ip_address": "10.0.100.3",
      "gateway": "10.0.2.2",
      "chef_role": "BCPC-Bootstrap"
    },
    "bcpc-dev-r1n1": {
      "ip_address": "10.0.100.11",
      "gateway": "10.0.2.2",
      "chef_role": "BCPC-Headnode"
    },
    "bcpc-dev-r1n2": {
      "ip_address": "10.0.100.12",
      "gateway": "10.0.2.2",
      "chef_role": "BCPC-Worknode"
    }
  }
}
$ vagrant ssh -c 'ip route ls dev eth0' r1n1
default via 10.0.2.2
10.0.2.0/24  proto kernel  scope link  src 10.0.2.15
Connection to 127.0.0.1 closed.
```

### CODE REVIEW

**Comment by kamidzi** [comment]
@kelvk: not sure if it necessary to always attempt to kill dhclient?

**Comment by kelvk** [comment]
It is to prevent it dhclient from overwriting network configuration. Did the interface restart stop `dhclient`?

**Comment by kamidzi** [comment]
Yes. Building fresh with this patch succeeds, suggesting no adverse effect from the change.

**Comment by kamidzi** [comment]
`ifup --force` allow reprovision but did not ensure termination of dhclient processes. A more minimal change results in:
```
$ vagrant ssh -c 'uptime && pgrep -fl dhclient' bootstrap && vagrant halt bootstrap && vagrant up
 16:00:48 up 1 min,  2 users,  load average: 0.98, 0.39, 0.14
4262 bash
Connection to 127.0.0.1 closed.
==> bootstrap: Attempting graceful shutdown of VM...
Bringing machine 'bootstrap' up with 'virtualbox' provider...
==> bootstrap: Clearing any previously set forwarded ports...
==> bootstrap: Fixed port collision for 22 => 2222. Now on port 2202.
==> bootstrap: Clearing any previously set network interfaces...
==> bootstrap: Preparing network interfaces based on configuration...
    bootstrap: Adapter 1: nat
    bootstrap: Adapter 2: intnet
    bootstrap: Adapter 3: intnet
    bootstrap: Adapter 4: intnet
==> bootstrap: Forwarding ports...
    bootstrap: 22 (guest) => 2202 (host) (adapter 1)
==> bootstrap: Running 'pre-boot' VM customizations...
==> bootstrap: Booting VM...
==> bootstrap: Waiting for machine to boot. This may take a few minutes...
    bootstrap: SSH address: 127.0.0.1:2202
    bootstrap: SSH username: vagrant
    bootstrap: SSH auth method: private key
==> bootstrap: Machine booted and ready!
==> bootstrap: Checking for guest additions in VM...
    bootstrap: The guest additions on this VM do not match the installed version of
    bootstrap: VirtualBox! In most cases this is fine, but in rare cases it can
    bootstrap: prevent things such as shared folders from working properly. If you see
    bootstrap: shared folder errors, please make sure the guest additions within the
    bootstrap: virtual machine match the version of VirtualBox you have installed on
    bootstrap: your host and reload your VM.
    bootstrap:
    bootstrap: Guest Additions Version: 4.3.36
    bootstrap: VirtualBox Version: 5.1
==> bootstrap: Setting hostname...
==> bootstrap: Configuring and enabling network interfaces...
==> bootstrap: Mounting shared folders...
    bootstrap: /chef-bcpc-host => /Users/kmidzi/build/chef-bcpc
    bootstrap: /chef-bcpc-files => /Users/kmidzi/.bcpc-cache
==> bootstrap: Machine already provisioned. Run `vagrant provision` or use the `--provision`
==> bootstrap: flag to force provisioning. Provisioners marked to run always will still run.
==> bootstrap: Running provisioner: delete-default-gw-on-eth0 (shell)...
    bootstrap: Running: /var/folders/2d/nj6nk1zn6f15y6zd4kz6qjk40000gp/T/vagrant-shell20171122-2601-1bq7url.sh
==> bootstrap: dhclient: no process found
==> bootstrap: Running provisioner: add-default-gw (shell)...
    bootstrap: Running: inline script
```

**Pull request merged**
