### PR TITLE
Separating cluster and hypervisor domains

### PR DESCRIPTION
**Pull request by erhudy**
Creating a PR for this for tracking purposes; not ready to merge just yet.

### CODE REVIEW

**Comment by erhudy** [comment]
Initial build looks fine; Chef didn't melt down and OpenStack services don't seem angry.

**Comment by mihalis68** [comment]
This looks good to me but will no longer merge cleanly.

**Comment by erhudy** [comment]
PR updated to merge.

**Comment by semenovroman** [comment]
Built a cluster from scratch from this branch - everything works as expected.

**Comment by mihalis68** [comment]
Looks good to me.

**Pull request merged**
