### PR TITLE
release: 8.2.5

### PR DESCRIPTION
**Pull request by jingqgeng**
David Comay (1):
      Address installation issue with `etcd3gw`

Jing Geng (1):
      allow upload and download from s3

Tyler Stachecki (1):
      ceph: Fix grace timer for mgr election

jgeng25 (2):
      update gitignore and readme for s3 for packer
      release: 8.2.5

Signed-off-by: jgeng25 <jgeng25@bloomberg.net>

### CODE REVIEW

**Review by mboruta1 — COMMENTED** [review]
Why does this PR have changes to other than `chef/cookbooks/bcpc.version`? Guess you made some changes @jingqgeng from when release-8.2.5 was branched out?

**Comment by tj90241** [comment]
+1, it looks like an extra commit snuck into the release branch "[address linter errors](https://github.com/bloomberg/chef-bcpc/pull/1953/commits/9b8296bad75a3f370dd28ee5c9aff069017bd4e4)"

**Comment by jingqgeng** [comment]
> 

Justin and I saw the linter errors yesterday. If they're not addressed, merging will be blocked for this PR.

**Comment by jingqgeng** [comment]
I removed the commit that fixes liner errors. Maybe when this is approved, it can be merged despite the linter errors?

**Review by tj90241 — APPROVED** [review]
shortlog in the commit is missing some of the recent/late commits, but not sure the adjustment is needed. lgtm

**Review by mboruta1 — APPROVED** [review]
Just need to wait for linter to finish running

**Pull request merged**
